---
title: \huge{Male-biased sexual selection, but not sexual dichromatism, predicts speciation
  in birds}
author:
- Justin G. Cally*\textsuperscript{§}, Devi Stuart-Fox\textsuperscript{§}, Luke Holman\textsuperscript{§}
  and Iliana Medina Guzmán\textsuperscript{§}
- '*\textit{justin.g.cally@gmail.com}'
bibliography: References/SS_Extinction.bib
output:
  pdf_document: default
  html_document:
    df_print: paged
header-includes: \usepackage{microtype} \usepackage[all]{hypcap} \usepackage{amsmath}
  \usepackage{booktabs} \usepackage{caption} \usepackage[labelfont=bf]{caption} \usepackage{titling}
  \pretitle{\begin{flushleft}\LARGE} \posttitle{\par\end{flushleft}\vskip 0.5em} \preauthor{\begin{flushleft}\large
  \lineskip 0.5em} \postauthor{\par\end{flushleft}} \predate{\begin{flushleft}\large}
  \postdate{\par\end{flushleft}} \usepackage{fancyhdr} \pagestyle{fancy} \fancyhead[L]{\textsl{\leftmark}}
  \rhead[]{Sexual selection predicts speciation} \usepackage[noabbrev,capitalise]{cleveref}
  \usepackage{titlefoot} \usepackage{amssymb} \usepackage{rotating} \usepackage{lineno}
  \linenumbers \usepackage{setspace}\onehalfspacing \usepackage[font={small}]{caption}
  \usepackage{epigraph} \setlength\epigraphwidth{5.25in} \setlength\epigraphrule{0pt}
  \setlength\beforeepigraphskip{1\baselineskip} \setlength\afterepigraphskip{2\baselineskip}
  \renewcommand*{\textflush}{flushright} \renewcommand*{\epigraphsize}{\footnotesize\itshape}
  \usepackage{titlesec} \titleformat{\section}{\normalfont\scshape\LARGE}{\thesection}{1em}{}
  \titleformat{\subsection}{\normalfont\Large}{\thesubsection}{1em}{} \titleformat{\subsubsection}{\normalfont\large}{\thesubsubsection}{1em}{}
  \usepackage{abstract} \renewcommand{\abstractnamefont}{\normalfont\Large} \usepackage[hang,
  flushmargin]{footmisc} \usepackage{hyperref}\hypersetup{colorlinks=true, hyperfootnotes=false,
  linkcolor=blue, filecolor=blue, urlcolor=blue} \usepackage{xcolor} \renewcommand\thefootnote{\textcolor{black}{\arabic{footnote}}}
  \raggedbottom
csl: References/evolution.csl
subparagraph: yes
abstract: Sexual selection is thought to shape phylogenetic diversity by affecting speciation or extinction rates. However, the net effect of sexual selection on diversification is hard to predict _a priori_, because many of the hypothesised effects on speciation or extinction have opposing signs and uncertain magnitudes. Here, we test whether the strength of sexual selection predicts variation in speciation and extinction rates across passerine birds (up to 5,812 species, covering most genera). We tested for associations between two measures of sexual selection (sexual dichromatism, plus an index that captures variance in sexual size dimorphism, polygyny, and male parental care), several environmental variables, and multiple measures of speciation and extinction rates. Our results show that male-biased sexual selection, but not sexual dichromatism, predicts speciation rates ($\lambda_{DR}$) in passerines, and found no evidence that this relationship varies with the environment. We also found a strong negative relationship between range size and speciation rate. There was no correlation between sexual selection and extinction rate **XXXXXX**. Our findings support the view that sexual selection is a potent evolutionary force that has shaped diversification in songbirds. \vspace{5mm}  \par\noindent
  \textbf{Keywords:} Speciation rate, Comparative analysis, Plumage dichromatism, Range size, Extinction rate.
---
\maketitle\unmarkedfntext{\textsuperscript{§}School of BioSciences, The University of Melbourne, Victoria, Australia.}

```{r, echo=FALSE}
MCC.DR.top <- readRDS('data/MCC.DR.top.rds')
MCC.ND.top <- readRDS('data/MCC.ND.top.rds')
MCC.Lambda.top <- readRDS('data/MCC.Lambda.top.rds')
MCC.Mu.top <- readRDS('data/MCC.Mu.top.rds')

#hpds
hpd.DR.top <- readRDS('data/hpd.DR.top.rds')
hpd.ND.top <- readRDS('data/hpd.ND.top.rds')
Armenta.hpd.DR.top <- readRDS('data/Armenta.hpd.DR.top.rds')

#Correlations
all.trees.join <- readRDS("data/all.trees.correlations.rds")
Harvey.vs.us <- readRDS("data/Harvey.vs.us.rds")

#Male bias SS
Subset.MCC.DR.top <- readRDS('data/Subset.MCC.DR.top.rds')
Subset.MCC.ND.top <- readRDS('data/Subset.MCC.ND.top.rds')
Subset.MCC.Lambda.top <- readRDS('data/Subset.MCC.Lambda.top.rds')
Subset.hpd.DR.top <- readRDS('data/Subset.hpd.DR.top.rds')
Subset.hpd.ND.top <- readRDS('data/Subset.hpd.ND.top.rds')
Subset.hpd.Lambda.top <- readRDS('data/Subset.hpd.Lambda.top.rds')
MCC.BAMM.df <- readRDS('data/MCC.BAMM.df.rds')

#path analysis
best_model <- readRDS('data/path_model.rds')
```

\newpage\phantomsection

<!-- Luke general comments:
In a few places you say things like "1000 random trees". To me this means trees with a random topology (which are sometimes used as some sort of null model), but I think you actually mean 1000 trees randomly sampled (without replacement) from the posterior of trees in Jetz et al. Is that right? If so, probably best to search for the word "random" and remove/reword it. 

I think it might make sense to call it "the index of male-biased sexual selection" throughout, including in the figures. Otherwise it's not clear when you mean the general phenomenon vs our measure of it. See what you think after reading my edits.
-->



# Introduction

Sexual selection results from competition between same-sex individuals for mates, their gametes, or associated resources, and in most species it predominently operates on males [@Kokko_Jennions2008; @Fromhage_2016; @Janicke_2016]. There is long-standing interest in the relationship between sexual selection and the processes of speciation, extinction, and phylogenetic diversification [e.g. @Lande_1981; @Lande_1982; @west1983sexual; @Seddon_2008; @Cooney_2018]. Recent empirical and methodological advances, such as growing evidence that sexual selection can profoundly affect many traits [e.g. life history, body mass, and immunocompetence; @Cally_2019], larger and more accurate phylogenies [@Jetz_2012], and new phylogenetic methods (**REFERENCES**), present new opportunities to test whether and how sexual selection drives diversification.

Several hypotheses predict a positive relationship across species between the strength of sexual selection and the rate of speciation and/or extinction. For example, sexual selection is involved in reinforcement, a speciation-promoting process in which members of different phylogenetic lineages evolve to avoid unproductive inter-lineage mating/fertilisation (**REF**). Additionally, sexual selection often operates on traits that can create reproductive isolation when they diverge between lineages, such as signals and preferences involved in mate selection [@Lande_1981; @Lande_1982; @Safran_2013], sperm-egg interactions [@swanson1998abalone], or genital morphology [@sloan2019genitalia]. Furthermore, sexual selection has been hypothesised to increase diversification by maintaining trait combinations that would be selected out under pure natural selection [@Bonduriansky_2011; @Radwan_2016], and by helping to prevent extinction by purging deleterious mutations [@Whitlock_Agrawal_2009], fixing beneficial ones [@Whitlock_2000], and accelerating adapation in environments [@Lorch_2003; @Candolin_2008; @Cally_2019]. Also, sexual selection sometimes favours individuals with rare phenotypes [@holman2013crozier], providing a source of diversifying selection that might increase the rate at which isolated populations diverge genetically.

Conversely, there are multiple ways in which sexual selection might hinder speciation or make extinction more likely. Firstly, sexual selection might promote extinction by favouring traits that improve mating success but reduce population fitness. For example, species with expensive sexual signals may be less resilient to environmental change [@Kokko_Brooks_2003], and sexual selection often creates a 'tragedy of the commons' by selecting for traits that increase the reproductive success of individuals while reducing population-wide productivity [e.g. infanticide, harassment, and reduced parental care by mate-seeking males; @RN37; @Kokko_Jennions2008; @Holman_Kokko_2013; @Fromhage_2016]. Sexual selection might also promote extinction by causing maladaptation ('gender load') in female traits that are genetically correlated with sexually-selected male traits [@Pischedda_2006; @harano2010intralocus; @Berger_2014; @Bonduriansky_Chenoweth_2009; @Pennell_2013]. Secondly, sexual selection might promote evolutionary stasis by ensuring that individuals with novel trait values have low mating success. 

Importantly, the relationship between sexual selection and diversification might be contingent on the environment. Theoretical work predicts that sexual selection should have a more positive effect on adaptation and population fitness in variable environments relative to stable ones [e.g. @Long_2012; @Connallon_Hall_2016], though the empirical evidence for this theory is mixed and largely limited to insects [@Cally_2019]. The mechanism underpinning this prediction is that the environment and the selective history of the population should influence the relative amounts of genetic variation at sexually concordant loci (*i.e.* loci where the same allele is fittest for both sexes) and sexually antagonistic loci (where different alleles are favoured in each sex). In stable environments, variation is thought to be preferentially depleted at sexually concordant loci, leading to stronger gender load and reduced net benefits of sexual selection [e.g. @Connallon_Hall_2016], and potentially to a more negative relationship between sexual selection and diversification rates across species. Conversely, sexual selection might be especially important at promoting local adaptation when the environment displays variability at the relevant spatial and temporal scales [e.g. @Boughman_2002; @Lorch_2003; @Maan_2011; @kokko2008condition]

<!-- .; causing displacement of male and female traits from their optimum. It follows from these predictions that populations with stronger sexual selection would have fitness benefits, allowing them to adapt to novel environments [*reviewed in* @Candolin_2008]. Additionally, sexual selection can reinforce local adaptations through mate choice on phenotypes that effectively advertise quality in a specific ecological context [@Boughman_2002; @Maan_2011]. For instance, beak morphology is a trait that arose under natural selection in several taxa and is now a trait under sexual selection [a.k.a. *magic traits*; @Servedio_2011]. In Darwin's finches (*Geospiza fortis*) divergent beak morphology is an adaptation to local food availability that has been maintained through assortative mating [@Huber_2007]. Through these synergetic effects sexual selection and natural selection (*e.g.* environmental variation over space and time) may lead to increased speciation rates.   -->

Birds have been a popular focus of macroevolutionary studies of sexual selection and diversification [*e.g.* @Barraclough_1995; @Morrow_Speciation_2003; @Seddon_2008; @Seddon_2013; @Huang_2014]. Birds are well-suited for this purpose due to their diverse and well-characterised mating systems and sexually-selected traits, and because their phylogenetic relationships are comparatively well-known. A 2011 meta-analysis covering 20 primary studies of birds and other taxa found a small but significant positive association between sexual selection and speciation, with the average effect size in birds stronger than in mammals but weaker than in insects or fish [@Kraaijeveld_2011]. However, there was large variation in effect size estimates across the 20 studies, likely reflecting differences in methodology, such as metrics used to characterise speciation and sexual selection, in addition to true biological differences. More recently, @Huang_2014 found no association between sexual dichromatism and speciation (*n* = 918 species) in a study using spectrophotometric measurements of museum specimens [@Armenta_2008] and tip-rate estimates from a molecular-only phylogeny [@Jetz_2012]. Similarly, @Cooney_2017 found no effect of sexual dichromatism on diversification across 1,306 pairs of species, using dichromatism scores provided by human observers. 

Here, we investigate the association between sexual selection and diversification in birds while building upon previous approaches in multiple ways. We use two measures of the strength of sexual selection: sexual dichromatism [*n* = 5,812 species; estimated from illustrations by @Dale_2015], as well as an index of male-biased sexual selection [*n* = 2,465 species; derived via principal components analysis by @Dale_2015], which captures (co)variation in sexual size dimorphism, social polygyny and paternal care. Most **OR ALL??** earlier macroevolutionary studies of this topic only quantified sexual selection using dichromatism, which is problematic since dichromatism does not always signal the presence of strong sexual selection and _vice versa_ [@Dale_2015]. For example, male and female dunnocks (_Prunella modularis_) are similarly coloured yet sexual selection appears to be strong [@davies1986re]. Furthermore, a recent comparative study found a negative relationship between dichromatism and another sexually-selected trait (song) across species, suggesting that a multi-trait focus would improve estimates of sexual selection intensity [@Cooney_2018]. Additionally, our analysis includes multiple ecological and environmental variables on diversification, allowing us to adjust for potential confounds, to identify environmental factors driving diversification, and to test whether environmental factors interact with sexual selection as theory predicts [@Connallon_Hall_2016]. We use multiple approaches for quantifying speciation and extinction rates at the tips of phylogenetic trees, including BAMM [Bayesian Analysis of Macroevolutionary Mixtures; *see*, @Beaulieu_2015; @Rabosky_Extinction_2016; @Moore_2016; @Rabosky_BAMM_flawed_2017], as well as older but reliable tip-rate statistics, such as diversification rate ($\lambda_{DR}$) and node density ($\lambda_{ND}$). Finally, we incorporate phylogenetic uncertainty into our analyses, improving over earlier work which assumed the statistically best-fitting phylogeny is correct.  \phantomsection


# Results
\phantomsection

## Variability across phylogenetic trees and speciation rate measures

**[Is it possible to move this later in the Results? It's possibly not ideal to start by highlighting the dependence of our conclusions on the methods we choose, and not mentioning our main non-null finding regarding the SS index. Having said that I can see a case for leaving it here too. - Luke]**

We first estimated speciation rates across the phylogeny, using the maximum clade credibility (MCC) tree, as well as 100 or 1000 trees sampled from the posterior distribution of trees in @Jetz_2012. Estimates of speciation rates varied between phylogenetic trees, especially for rates calculated by BAMM ($\lambda_{BAMM}$ and $\mu_{BAMM}$), where the 95% highest posterior density (HPD) interval across 100 trees was >20-fold larger than the **95% confidence interval [SHOULD THIS BE HPD TOO?]** calculated for the MCC tree. Conversely, for our estimates of diversification rate ($\lambda_{DR}$) and node density ($\lambda_{ND}$), the 95% HPD interval across 1,000 trees was near-identical to the 95% confidence interval calculated for the MCC tree (\href{https://justincally.github.io/SexualSelection_Speciation/#analysis}{Table S9}). Given the computational requirements of BAMM, the great majority of earlier studies have based their estimates on a single consensus tree, and so the inconsistency of the BAMM estimates between different phylogenies with similar statistical support is notable. Mean measures of speciation rate across 100 trees were positively correlated between measures (DR - BAMM: *r*=`r round(cor(all.trees.join$DR, all.trees.join$mean.lambda), digits = 2)`, DR - ND: *r*=`r round(cor(all.trees.join$DR, all.trees.join$ND), digits = 2)`, ND- BAMM: *r*=`r round(cor(all.trees.join$ND, all.trees.join$mean.lambda), digits = 2)`; \href{https://justincally.github.io/SexualSelection_Speciation/#additional_figures_and_tables}{Figure S15}). Given that the calculation of BAMM rates can be affected by the settings of the run and the use of different priors, we compared the estimate of our MCC tree with that of previous published analyses on birds, and found a high correlation (*r*=`r round(cor(Harvey.vs.us$mean.lambda, Harvey.vs.us$Harvey.lambda, use = "pairwise"), digits = 2)`, \href{https://justincally.github.io/SexualSelection_Speciation/#bamm_measures_of_speciation_and_extinction}{Figure S8}). Full details of the BAMM results are presented as supplementary materials.   

\phantomsection
## No evidence that the relationship between sexual selection and speciation depends on environmental variability

**[I think this part should go after the next 2 sections, as it's a more confusing being about interactions, and we should preserve the order of ideas from the Abstract and Intro. - Luke]**

We next fit Phylogenetic Generalized Least Squares (PGLS) models with **2-way [CORRECT?]** interaction terms between each measure of sexual dichromatism/selection and the five measures of environmental variability (seasonal temperature variation, log-range size, long-term temperature variation, spatial temperature variation, and NPP) and compared them using AICc model selection. However, no interaction terms were present in the top models ($\delta$ AICc > 4) for any measure of speciation ($\lambda_{DR}$, $\lambda_{ND}$, $\lambda_{BAMM}$) or sexual selection (RGB values, spectrophotometry and male-biased sexual selection; $\delta$ AICc > 4; \href{https://justincally.github.io/SexualSelection_Speciation/#pgls_models_on_dr_and_nd}{Table S5}, \href{https://justincally.github.io/SexualSelection_Speciation/#pgls_models_on_bamm_estimates}{Table S6}, \href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Table S10}, \href{https://justincally.github.io/SexualSelection_Speciation/#analysis_using_male-biased_measure_of_sexual_selection}{Table S13}). Thus we found no evidence that the effect of sexual selection on speciation is dependent on our measures of environmental variation. Furthermore, we found no evidence that these environmental factors (seasonal temperature variation, long-term temperature variation, spatial temperature variation, and NPP) predict speciation independently from sexual dichromatism/selection (\autoref{model_results}, \href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Figure S11}).   
\phantomsection

## No evidence that sexual dichromatism affects speciation

We found no evidence that species with increased sexual dichromatism have higher or lower rates of speciation. Using three different measures of speciation ($\lambda_{DR}$, $\lambda_{ND}$, $\lambda_{BAMM}$) as the response variable, the effect of sexual dichromatism was not significant in any PGLS model based on tip-rate estimates and correlation structures from the MCC tree. Specifically, sexual dichromatism showed no association with $\lambda_{DR}$ ($\beta$ = `r formatC(MCC.DR.top[["coefficients"]][["SDi"]], format = "e", digits = 3)`, p = `r round(anova(MCC.DR.top)[["SDi","p-value"]], digits = 3)`; \autoref{model_results}a, \autoref{Speciation_Figure}a) or $\lambda_{ND}$ ($\beta$ = `r formatC(MCC.ND.top[["coefficients"]][["SDi"]], format = "e", digits = 3)`, p = `r round(anova(MCC.ND.top)[["SDi","p-value"]], digits = 3)`; \autoref{model_results}a). Furthermore, speciation rates from BAMM ($\lambda_{BAMM}$) were also unaffected by sexual dichromatism ($\beta$ = `r formatC(MCC.Lambda.top[["coefficients"]][["SDi"]], format = "e", digits = 3)`, p = `r round(anova(MCC.Lambda.top)[["SDi","p-value"]], digits = 3)`; \autoref{model_results}a). PGLS analyses using sexual dichromatism (*n* = 581) measured by spectrophotometry [@Armenta_2008] yielded results concordant with the full dataset; *i.e.* no association between sexual dichromatism and speciation (\href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Figure S11}). Our results from models based on the MCC tree are largely corroborated by model estimates from PGLS analyses of the rates and correlation structures from 1,000 trees (for $\lambda_{DR}$, $\lambda_{ND}$) and 100 trees for $\lambda_{BAMM}$. The HPD intervals show model estimates are distributed around zero when using complete taxon sampling models and RGB measures of sexual dichromatism (\autoref{model_results}a, \href{https://justincally.github.io/SexualSelection_Speciation/#pgls_model_summary}{Table S8}). For PGLS models using spectrophotometry-based measures of sexual dichromatism, the estimates from the 100 trees in the $\lambda_{DR}$ models are positively skewed (HPD Interval = `r formatC(Armenta.hpd.DR.top$Colour.discriminability, format = "e", digits = 3)`) but normally distributed around zero for $\lambda_{ND}$ and $\lambda_{BAMM}$ (\href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Table S12}).  \phantomsection

## Male-biased sexual selection increases speciation rate

We found a significant positive association between male-biased sexual selection (*n* = 2,465) and $\lambda_{DR}$ for the MCC tree ($\beta$ = `r formatC(Subset.MCC.DR.top[["coefficients"]][["Sexual_selection_ppca"]], format = "e", digits = 3)`, p = `r round(anova(Subset.MCC.DR.top)[["Sexual_selection_ppca","p-value"]], digits = 3)`; \autoref{model_results}b). However, this association was not significant for the other two measures of speciation rate ($\lambda_{ND}$: $\beta$ = `r formatC(Subset.MCC.ND.top[["coefficients"]][["Sexual_selection_ppca"]], format = "e", digits = 3)`, p = `r round(anova(Subset.MCC.ND.top)[["Sexual_selection_ppca","p-value"]], digits = 3)`; $\lambda_{BAMM}$: $\beta$ = `r formatC(Subset.MCC.Lambda.top[["coefficients"]][["Sexual_selection_ppca"]], format = "e", digits = 3)`, p = `r round(anova(Subset.MCC.Lambda.top)[["Sexual_selection_ppca","p-value"]], digits = 3)`; \autoref{model_results}b). The distribution of estimates from PGLS models on 1,000 trees was similar to the estimate from the MCC tree: among the 1,000 trees there was a positive association between sexual selection and $\lambda_{DR}$ (HPD Interval = `r formatC(Subset.hpd.DR.top$Sexual_selection_ppca, format = "e", digits = 3)`), and a smaller positive association between sexual selection and $\lambda_{ND}$ (HPD Interval = `r formatC(Subset.hpd.ND.top$Sexual_selection_ppca, format = "e", digits = 3)`; ) as well as the 100 models using $\lambda_{BAMM}$ (HPD Interval = `r formatC(Subset.hpd.Lambda.top$Sexual_selection_ppca, format = "e", digits = 3)`). Complete HPD intervals for models using male-bias sexual selection PPCA as a predictor can be found within \href{https://justincally.github.io/SexualSelection_Speciation/#analysis_using_male-biased_measure_of_sexual_selection}{Table S15}.  \phantomsection

## Species with smaller ranges have increased rates of speciation

Based on $\lambda_{DR}$ and $\lambda_{ND}$ tip-rate metrics of speciation, we found a negative association between range size and speciation; that is, species with smaller ranges show marginally higher values for $\lambda_{DR}$ and $\lambda_{ND}$. This negative association was small but significant for models using the MCC tree ($\lambda_{DR}$: $\beta$ = `r formatC(MCC.DR.top[["coefficients"]][["log(range.size.m2)"]], format = "e", digits = 3)`, p = `r round(anova(MCC.DR.top)[["log(range.size.m2)","p-value"]], digits = 3)`; $\lambda_{ND}$: $\beta$ = `r formatC(MCC.ND.top[["coefficients"]][["log(range.size.m2)"]], format = "e", digits = 3)`, p = `r round(anova(MCC.ND.top)[["log(range.size.m2)","p-value"]], digits = 3)`; \autoref{model_results}a, \autoref{Speciation_Figure}). This association was also evident across the estimates from models using the 1,000 trees ($\lambda_{DR}$: HPD Interval = `r formatC(hpd.DR.top[[2]], format = "e", digits = 3)`; $\lambda_{ND}$: HPD Interval = `r formatC(hpd.ND.top[[2]], format = "e", digits = 3)`; \autoref{model_results}a). Subset models with reduced sample size and different measures of sexual selection --- but the same measure of range size --- showed equivocal evidence that range size is negatively associated with speciation. Range size significantly predicted $\lambda_{DR}$ (\autoref{model_results}b) using data subset for male-biased sexual selection (*n* = 2,465) but not $\lambda_{ND}$ or $\lambda_{BAMM}$. Models using data subset for spectrophotometry-based dichromatism (*n* = 581) gave non-significant estimates for the effect of range size on all measures of speciation (\href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Figure S11}, \href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Table S11}, \href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Table S12}). Because the range size dataset is the same across the three data subsets we draw our conclusions from the models with the highest power using near-complete taxon sampling (*n* = 5,812).  \phantomsection

## Phylogenetic path analysis

Using a phylogenetic path analysis, we found multiple significant paths between variables used in the PGLS (\autoref{Path_Analysis}; \href{https://justincally.github.io/SexualSelection_Speciation/#phylogenetic_path_analysis}{Figure S14}). There was a modest effect of male-biased sexual selection on sexual dimorphism ($\beta$ = `r round(best_model[["coef"]][2,4], digits = 2)`). Additionally, temperature seasonality weakly affected sexual dimorphism ($\beta$ = `r round(best_model[["coef"]][1,4], digits = 2)`) and strongly affected range size ($\beta$ = `r round(best_model[["coef"]][1,3], digits = 2)`). This suggests an indirect effect of temperature seasonality on $\lambda_{DR}$ ($\beta_{indirect}$ = `r round(best_model[["coef"]][1,3]*best_model[["coef"]][3,5], digits = 2)`; \autoref{Path_Analysis}), given the negative association we identified between $\lambda_{DR}$ and range size in PGLS models.  \phantomsection

## Extinction rate

We found no evidence that extinction ($\mu_{BAMM}$) was impacted by the extent of sexual dichromatism for full-taxon sampling ($\beta$ = `r formatC(MCC.Mu.top[["coefficients"]][["SDi"]], format = "e", digits = 3)`, p = `r round(anova(MCC.Mu.top)[["SDi","p-value"]], digits = 3)`; \autoref{model_results}a), nor spectrophotometry-based measures of sexual dichromatism (\href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Figure S11}, \href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Table S11}, \href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Table S12}) or male-biased sexual selection (\autoref{model_results}b, \href{https://justincally.github.io/SexualSelection_Speciation/#analysis_using_male-biased_measure_of_sexual_selection}{Table S14}, \href{https://justincally.github.io/SexualSelection_Speciation/#analysis_using_male-biased_measure_of_sexual_selection}{Table S15}).  

![Model estimates (**a**) for the effect of log-range size and sexual dichromatism on speciation and extinction rates using PGLS analyses with the sexual dichromatism dataset (RGB values, *n* = 5,812). (**b**) depicts the scatter plot of speciation rate ($\lambda_{DR}$) and log-range size with the model estimate presented as a dashed line. (**c**) shows the scatter plot of speciation rate ($\lambda_{DR}$) and male-biased sexual selection (*n* = 2,465). Similar to (**a**), (**d**) presents model estimates for PGLS analyses using a restricted dataset with measures of male-biased sexual selection (*n* = 2,465) and shows the effect of log-range size and male-biased sexual selection on speciation and extinction rates. Both datasets were used for analyses with three measures of speciation ($\lambda_{DR}$, $\lambda_{ND}$, $\lambda_{BAMM}$) and one measure of extinction ($\mu_{BAMM}$) as response variables. The numerical values for the model estimates using the MCC tree and HPD intervals of estimates from 1,000 random trees (for $\lambda_{DR}$ and $\lambda_{ND}$) or 100 random trees for $\lambda_{BAMM}$ and $\mu_{BAMM}$ can be found in the ESM. Density curves are based on model estimates from 1,000/100 trees and the circle below with error bars is the estimate and 95% CIs from the MCC tree. For this figure we removed outliers from estimates coming from the 100 random trees for BAMM models in order to be able to visualise the MCC 95% CIs. \label{model_results}](Figures/Estimates_and_scatter_edit.pdf)  

![Speciation rate ($\lambda_{DR}$) across all passerine birds (*n* = 5,965) with estimates of sexual dichromatism, range size available for 5,812 species and male-biased sexual selection available for 2,465 species. Across these species there was a small but significant negative association between $\lambda_{DR}$ and log-range size as well as a significant positive association between $\lambda_{DR}$ and male-biased sexual selection but no significant association between $\lambda_{DR}$ and sexual dichromatism based on RGB measures. $\lambda_{DR}$ are those from the MCC tree and images of birds are from the _Handbook of the Birds of the World_. Clockwise the species are: _Sporophila bouvronides_, _Geospiza magnirostris_, _Atlapetes leucopterus_, _Euphonia rufiventris_, _Euplectes franciscanus_, _Promerops gurneyi_, _Phainopepla nitens_, _Zosterops erythropleurus_, _Acrocephalus australis_, _Progne cryptoleuca_, _Mayrornis schistaceus_, _Paradisaea rubra_, _Pachycephala pectoralis_, _Malurus pulcherrimus_, _Cranioleuca curtata_, _Cercomacra manu_, _Muscisaxicola capistratus_, _Lepidothrix coeruleocapilla_. Edge colours for the terminal branch correspond to $\lambda_{DR}$ but all precluding branches have been generated for graphical purposes using ancestral character state estimation and should not be interpreted. \label{Speciation_Figure}](Figures/DRSpeciationFigure.pdf)  

![Path analysis of evolutionary and ecological variables. Arrows represent direct effects with the direction of effect corresponding to colours (blue = positive, red = negative). The numeric values are standardised regression slopes and the asterisks indicates that the 95% confidence intervals of this estimate do not overlap with zero. The confidence intervals were obtained from 500 bootstrapped iterations and the data used in this analysis was subset to species with both sexual dichromatism and male-biased sexual selection measures (*n* = 2,465). \label{Path_Analysis}](Figures/Path_Analysis.pdf)  

\newpage\phantomsection

# Discussion

We found evidence that the composite index of male-biased sexual selection, but not measures of sexual dichromatism, is correlated with the rate of speciation in passerine birds. The absence of a detectable correlation between sexual dichromatism and speciation rate was consistent across different measures of speciation ($\lambda_{DR}$, $\lambda_{ND}$ and $\lambda_{BAMM}$) and both measures of dichromatism (spectral and RGB), and it cannot be explained by a difference in statistical power since the sample size for the dichromatism analyses was much larger. These findings reaffirm the conclusions of previous, smaller studies in which sexual dichromatism was measured using spectrophotometry [@Huang_2014] or human observers [@Cooney_2017]. The correlation between speciation rate and the index of male-biased sexual selection (which encapsulates variation in sexual size dimorphism, social polygyny, and paternal care) was statistically significant for $\lambda_{DR}$, but not for $\lambda_{ND}$ and $\lambda_{BAMM}$, although the estimated direction and magnitude of the correlation was broadly similar across all three measures. Interestingly, we also found a consistent negative relationship between range size and speciation rate, at least when this rate was quantified using $\lambda_{DR}$ and $\lambda_{ND}$. None of the bioclimatic measures of environmental variability that we investigated (*i.e.*, temperature seasonality, long-term temperature variation, and spatial temperature variation) significantly predicted speciation rate.  

The difference in findings between the analyses of sexual dichromatism _versus_ the index of sexual selection is noteworthy, because the majority of earlier studies used dichromatism alone as their proxy for sexual selection [*e.g.*, @Barraclough_1995; @Seddon_2013; @Morrow_Speciation_2003; @Owens_1999; @Huang_2014]. Given our findings, and the modest correlation between dichromatism and the sexual selection index [$r = 0.34$; @Dale_2015], we hypothesise that sexual dichromatism may not be a robust proxy for sexual selection. Although dichromatism clearly reflects sexual selection to some extent, it is possibly that it is too indirect a measure to detectany association with speciation rate, even with a high sample size. There are several reasons why the use of sexual dichromatism as a proxy for sexual selection is problematic. Firstly, sexual dichromatism can evolve for reasons other than sexual selection, such as when males and females occupy different ecological niches [@Wallace_1889; @Kottler_1980; @Slatkin_1984; @Shine_1989] or experience different selective pressures in contexts other than competition for mates [@Price_2014]. For example, in superb fairy-wrens (*Malurus cyaneus*) female colouration has probably evolved in response to spatial variation in predation pressure, increasing dichromatism [@Medina_2017]. Ecological selection on sexual dichromatism was implicated by our path analysis, which found that sexual dichromatism is positively affected by temperature seasonality (a measure of environmental variation), albeit weakly. Secondly, colour is only one of the traits subject to sexual selection [@Miles_2018; @Cally_2019]. For instance, sexual selection may promote investments in other mating signals (*e.g.* song) that trade-off against plumage colour, leading to variable investment in different sexually selected signals across species [@Cooney_2018]. Lastly, not all plumage colouration honestly reflects mate quality. A recent meta-analysis found that converted carotenoids (but not carotenoids sourced from the diet) predict mate quality through improvements in parasite resistance and reproductive success [@Weaver_2018]. Thus, bright colours may signal direct benefits or 'good genes' in some species but not others, and some of the colours used to calculate dichromatism might be more functionally relevant than others.

In-line with some theoretical predictions and previous studies [@Kraaijeveld_2011] we found that male-biased sexual selection increases speciation rate, at least when speciation is measured by $\lambda_{DR}$. Additionally, we found that this association appears to be independent of net primary productivity and spatiotemporal variation in the environment. The lack of an effect of these environmental variables on speciation rate has several possible interpretations. Firstly, the effects of sexual selection on adaptation and speciation may depend on the type of environmental variability under which the species is evolving. Specifically, speciation rates might be impacted by genetic constraints on adaptation, that vary across environments. Theory suggests that sexual antagonism (which is often exacerbated in species with strong sexual selection) may be lower in habitats experiencing cyclical environmental variation (*e.g.* seasonality), relative to those experiencing directional change in the environment [@Connallon_Hall_2016]. Another possibility is that the environmental predictors we chose may not account for the key ecological sources of selection that interact with sexual selection to drive speciation. For example, our study does not include direct measure of food availability or the severity of predation and parasitism, which are both hypothesised to affect sexual selection and speciation [*reviewed in* @Maan_2011]. Finally, it is possible that environmental variability genuinely has little effect on speciation rates, at least in the taxa investigated here.  

The most robust finding in our study is the finding that species with smaller ranges have elevated speciation rates. This result is similar to a study of 329 amphibian genera, which found higher diversification rates in taxa with smaller range size [@Greenberg_2017]. Intuitively, large range size should promote speciation by creating more opportunities for geographic barriers to form [@Rosenzweig_1995; @Castiglione_2017]. However, the opposite pattern is also plausible because birds with limited dispersal or more specialised niches can have more fragmented populations, which would promote vicariant divergence and higher speciation rates [@Birand_2012; @Claramunt_2012; @Jablonski_2003]. **Please check this sentence, I didn't understand the original but I tried to re-draft for clarity** It is also possible that high speciation rates cause smaller range sizes, rather than the other way around, for example because repeatedly-speciating lineages tend to fill niches in ways that hinder the geographical expansion of new species [@Rosenzweig_1995; @Weir_2011; @Price_2014]. However, species undergoing adaptive radiation in new habitats are unlikely to be limited by competition for resources from existing taxa. Across islands, we expect to see a correlation between speciation and small range size because small islands often reflect newly formed environments with empty niches. **As a jerk reviewer, I would say "can't you re-run it without the island radiations??"** Thus, our findings might be driven by island radiations (*e.g.* "Darwin's finches", *Geospiza* spp.). One further explanation for the negative association between range size and sexual dichromatism/sexual selection is the potential bias of taxonomic classification, whereby over-splitting of species in clades with large ranges leads to increased recent phylogenetic branching as well as smaller ranges.  

In addition to speciation, sexual selection is hypothesised to affect extinction. Using the model-based approach of BAMM, we found no association between the estiamted extinction rate and sexual dichromatism, male-biased sexual selection, or our measures of environmental variability. However, these extinction results should not be regarded as definitive because extinction is notoriously difficult to estimate accurately from phylogenies, principally because different combinations of speciation and extinction rates can give rise to similar patterns of diversity [see @Rabosky_Extinction_2016]. Phylogenetic methods such as BAMM allow for speciation and extinction rates to be estimated using moderately-sized phylogenies, although the ability of BAMM to model evolutionary rate shifts and extinction rates is debated [*see*, @Beaulieu_2015; @Rabosky_Extinction_2016; @Moore_2016; @Rabosky_BAMM_flawed_2017]. Additionally, while several tip-rate estimates exist for speciation rate (*e.g.*, $\lambda_{DR}$ and $\lambda_{ND}$), tip-rate estimates of extinction rate are difficult to obtain without complex Bayesian models which are sensitive to sampling bias [@Davis_2013]. Although extinction rates can be inferred from alternative sources, such as the fossil record [@Martins_2018], direct observation extinction, or IUCN red list status [@Greenberg_2017], each approach has its limitations. Across the passerine bird phylogeny, we found that BAMM often produced homogeneous speciation and extinction rates for smaller clades showing few rate shifts, which might reduce our power to detect small differences in extinction rates among closely-related taxa [@Rabosky_BAMM_flawed_2017; @Rabosky_diversification_2018]. Thus, this methodological constraint likely decreases our ability to accurately measure the correlation between metrics of sexual selection and the probability of extinction.   

One outcome of our analyses was that different measures of speciation rates presented different results. This is not completely surprising, because each of the rates is calculated differently (see @Rabosky_diversification_2018). For instance, $\lambda_{DR}$ is weighted more towards speciation events close to the tips and allows more rate heterogeneity compared to BAMM estimates. This leads to greater variation in $\lambda_{DR}$ relative to the BAMM estimates, potentially explaining the difference in results. The BAMM estimates were also more sensitive to phylogenetic uncertainty.

To summarise, we have shown that male-biased sexual selection, but not sexual dichromatism, predicts speciation in passerines, and that this relationship is not markedly affected by environmental variability. These findings imply that sexual dechromatism is not a reliable proxy for sexual selection, and that alternative measures of sexual selection are more directly related to diversification. Our results also add indirect suppport to the hypothesis that sexual selection promotes adaptation, which has implications for conservation [@Holman_Kokko_2013] and captive breeding programs for threatened species [@Charge_2014]. Furthermore, our finding that high speciation rate is associated with smaller range size highlights the threat to the persistence of rapidly-speciating lineages in a world with increased habitat loss and anthropogenic stress. This concern arises as the best predictor of extinction risk is range size [@Harris_2008] and the association found here implies that many newly-speciated clades have small range sizes and could thus be at greater risk of extinction.  

\newpage\phantomsection
# Materials and methods

We examined the effect of sexual selection on speciation and extinction rate in 97% of passerines (*n* = 5,812 species; 58% of all birds). Specifically, we (*i*) compiled datasets for sexual dichromatism/selection strength and environmental variability, (*ii*) obtained estimates of speciation and extinction rates across passerines, and (*iii*) conducted phylogenetic generalized least-squares (PGLS) regressions. Analyses are documented with reproducible code in the \href{https://justincally.github.io/SexualSelection_Speciation/}{Electronic Supplementary Material (ESM)}.  \phantomsection

## Compiling data for sexual selection and environmental stress
\phantomsection

### Sexual dichromatism

We used a previously-published measure of sexual dichromatism for 5,983 species of passerines [@Dale_2015]. Briefly, @Dale_2015 obtained sex-specific RGB (red-green-blue) values across six body patches (nape, crown, forehead, throat, upper breast, and lower breast) from _Handbook of the Birds of the World_ [@delhoyo2011]. The relative contribution of male and female RGB colour values were averaged across body patches and provide 'male-like' and 'female-like' plumage scores. Here we use the absolute difference between male and female plumage scores as an estimate of sexual dichromatism. Additionally, we used another measure of dichromatism corresponding to colour distance in avian colour space derived from spectral data [@Armenta_2008]. These measurements include variation in the ultraviolet and bird-visible range and --- unlike the RGB measures --- are sourced from museum specimens as opposed to illustrations. The spectrophotometry data covers only 581 passerine species (10-fold fewer than the RGB data), although there was a substantial correlation between the two dichromatism measures ($r = 0.79$; \href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Figure S10}).  \phantomsection

### Male-biased sexual selection

Because sexual dichromatism is presumably imperfectly correlated with variation in the strength of sexual selection across taxa, we sourced an additional measure of sexual selection, also from @Dale_2015, referred to here as the 'index of male-biased sexual selection'. This index is the first principal component from a phylogenetic principal component analysis (PPCA) of three characteristics possitively associated with sexual selection (sexual size dimorphism, social polygyny and [lack of] paternal care). This measure of male-biased sexual selection is available for only 2,465 species, and shows a moderate correlation with the RGB measure of sexual dichromatism ($r = 0.34$; \href{https://justincally.github.io/SexualSelection_Speciation/#analysis_using_male-biased_measure_of_sexual_selection}{Figure S12}).  \phantomsection

### Environmental variables 

We obtained estimates of species range size using expert range maps [@birdlife_2017]. Because of taxonomic changes to 1,230 species in the _Birdlife_ database [@delhoyo_2016] we manually matched these taxa with the names used in the sexual dichromatism dataset [@Dale_2015]. From these distributions, we obtained estimates of climatic conditions that each species is exposed to. That is, we took 1,000 random point samples in each range and extracted 19 present-day bioclimatic variables (representing a variety of biologically relevant annual trends in temperature and precipitation) with 30-second (~1 km^2^) spatial resolution [@Fick_2017]. From these values, we obtained means and standard deviations for each species. Using the same spatial sampling, we extracted means and standard deviations of bioclimatic variables from the paleoclimate during the last interglacial [LIG; 120,000 - 140,000 years ago; @Otto-Bliesner_2006]. We include estimates of climate variability during recent evolutionary history as they may be a better indicators of environmental effects on speciation than present-day  environmental variability. Furthermore, to estimate variability in the energy available to species, we obtained the mean and standard deviation of net primary productivity (NPP) values between 2000 - 2015 across each species distribution. Estimates of NPP had 30-second resolution and were obtained through MODIS (Moderate Resolution Imaging Spectroradiometer) primary production products stage 3 [MOD17A3; @Zhao_2005]. Using these data, which we provide as a potentially useful data resource (see \href{https://justincally.github.io/SexualSelection_Speciation/}{ESM}), we generated five predictors of speciation associated with different patterns in environmental variability (see below).  \phantomsection

### Generating biologically relevant predictors for environmental stress

Given that stressful environments are expected to interact with sexual selection and have a positive effect on adaptation [@Cally_2019], we used the extracted environmental variables from each species range size to create predictors of environmental variation/stress. Firstly we used (*i*) the average NPP in each species' range and (*v*) the log-transformed range size as potentially informative predictors of speciation rates. We also used three environmental predictors derived from bioclimatic data. These predictors relate to seasonal climate variation, spatial climate variation and long-term climate variation. To obtain seasonal climate variation we used (*iii*) mean values of temperature seasonality (BIO4) for each range. (*iV*) To estimate levels of spatial environmental variation a species may endure we used the first principle component (PC1) from a PCA on standard deviations from all bioclimatic variables, excluding temperature and precipitation seasonality (BIO 4 and BIO15). PC1 was heavily loaded towards bioclimatic variables relating to temperature, thus PC1 reflects the variation in temperature across a species' range (\href{https://justincally.github.io/SexualSelection_Speciation/#generating_biologically_relevent_predictors}{Table S1}). Species range is a potentially informative predictor of speciation and extinction, so we controlled for the correlation between environmental spatial variation and range size --- where larger ranges have larger variation in PC1 --- by using the residuals of a fitted general additive model (GAM; \href{https://justincally.github.io/SexualSelection_Speciation/#generating_biologically_relevent_predictors}{Figure S1}) as a predictor. To obtain long-term variation in climates for each species range we take (*v*) the first principal component of the absolute difference in the bioclimatic variables between the LIG and current values. Similar to spatial variation, the long-term climate variation is primarily loaded to temperature differences between the LIG and current climates (\href{https://justincally.github.io/SexualSelection_Speciation/#long_term_climate_variability_(lig_anomaly)}{Table S2, Figure S2}). The five predictors of environmental variability are not strongly correlated (\href{https://justincally.github.io/SexualSelection_Speciation/#correlations_between_environmental_predictors}{Figure S3}). Details and ``R`` code to generate these predictors can be found within the \href{https://justincally.github.io/SexualSelection_Speciation/}{ESM}.  \phantomsection

## Estimating extinction and speciation  

Phylogenetic information was obtained from www.birdtree.org [@Jetz_2012]. We used a maximum clade credibility (MCC) tree from 2,500 samples of the posterior distribution (*n* = 5,965) as the main phylogenetic hypothesis in our comparative analysis. Additionally, a random draw of full trees (including species without genetic data) from the posterior distribution of phylogenetic trees was used for diversification analyses using tip-rate measures (1000 trees) and BAMM (100 trees)[@Rabosky_2014]. These trees used a 'Hackett backbone' [@Hackett_2008] and were constructed using a pure birth (Yule) model. We calculated three different tip-rate metrics of speciation and one of extinction across all trees.  

Firstly, we obtained two tip-rate metrics of speciation using statistics derived from the properties of the nodes and branches along root-to-tip paths of the phylogeny. Node density (ND) is a simple statistic calculating the density of nodes from the phylogenetic root to the tip, while the log-transformed equal splits (logES), also known as diversification rate (DR) [*e.g.*, @Jetz_2012; @quintero_2018; @Rabosky_fish_2018], is derived from the sum of edge lengths branching from a node, with each edge towards the root having the length down-weighted. Studies have suggested that DR and ND (henceforth referred to as $\lambda_{DR}$ and $\lambda_{ND}$) are more reflective estimates of speciation than diversification; this is because $\lambda_{DR}$ and $\lambda_{ND}$ cannot account for whole-clade extinctions and thus under-estimate extinction rate, which makes the composite measure of diversification more dependent on speciation [@Belmaker_2015; @Rabosky_diversification_2018]. Therefore, $\lambda_{DR}$ is a measure of speciation rate more heavily weighted to recent speciation events while $\lambda_{ND}$ measures speciation across the root-to-tip path. These tip-rate measures are alternatives to state-dependent diversification models such as Quantitative State Speciation-Extinction (QuaSSE); but, based on previous simulation studies, $\lambda_{DR}$ and $\lambda_{ND}$ are robust and intuitive measures that provide high power and low false discovery rate with large phylogenies when incorporated into Phylogenetic Generalized Least Squares (PGLS) models [@Harvey_essim_2017].  

Secondly, we used BAMM to model the dynamics of speciation and extinction across the 100 phylogenetic trees [@Rabosky_2014]. This software uses a Bayesian approach (reversible-jump Markov Chain Monte Carlo) to generate probability distributions of evolutionary rate-shift configurations with variable speciation and extinction rates. Importantly, these models provide tip-rate estimates of speciation and extinction rate. The parameters of the 100 BAMM runs are detailed in full in the \href{https://justincally.github.io/SexualSelection_Speciation/#set_up_bamm_parameters}{ESM}; briefly, we used a time-variable model with 100 expected number of shifts and prior rates set from the initial speciation and extinction values using the ``BAMMtools`` R package [@bammtools_2014]. Each BAMM model (one MCC tree and 100 random draws of the posterior) was run for 100 million generations, and given the computationally intensive nature of BAMM, runs were conducted across multiple CPUs. Each run of BAMM reached convergence with effective sample size (ESS) of MCMC (Markov Chain Monte Carlo) samples surpassing 200 (an arbitrary value, above which posterior distributions can often be accurately inferred) for the key model parameters of log-likelihood and number of rate shifts (\href{https://justincally.github.io/SexualSelection_Speciation/#bamm_measures_of_speciation_and_extinction}{Table S3}, \href{https://justincally.github.io/SexualSelection_Speciation/#bamm_measures_of_speciation_and_extinction}{Table S4}). Further details of BAMM parameters and output are available in the \href{https://justincally.github.io/SexualSelection_Speciation/}{ESM}, with tip-rate means and variances provided. Additionally, given the variability in BAMM estimates, we also provide analysis of BAMM shift configurations and tip-rate estimates from our run on the MCC tree and within a BAMM run on the MCC tree from a genetic-only phylogeny across all birds [@Harvey_2017]. All analyses were conducted on log-rates.  \phantomsection

## Phylogenetic comparative analysis

To test the association between speciation/extinction and sexual selection, environmental variability and their interaction, we used phylogenetic least squares (PGLS) models in the ``nlme`` package [@nlme_2018]. Firstly, we conducted model selection to compare models in which $\lambda_{DR}$, $\lambda_{ND}$, $\lambda_{BAMM}$ or $\mu_{BAMM}$ were the response variable: these tip-rate estimates all came from the same MCC tree (derived from 2,500 draws of the posterior distribution in @Jetz_2012). For models of $\lambda_{BAMM}$ and $\mu_{BAMM}$ we used the inverse of the variance associated with each tip rate estimate as weights, to account for the variable precision of the estimates provided by BAMM. The most complicated model in each set under comparison contained one of the measures of sexual selection (sexual dichromatism or the index of male-biased sexual selection), all of the environmental measures (*i.e.* log-transformed range size, seasonal temperature variation, spatial temperature variation, long-term temperature variation, and NPP), and all of the 2-way interactions between sexual selection and each of the environmental measures. The simpler models contained all of the same main effects, but had fewer 2-way interaction terms (potentially none). Model selection was done in ``MuMIn`` using the ``dredge`` function [@MuMIn_2017]. Using the terms from the top-ranked model (ranked by AICc), we ran the equivalent model for each of the 1,000 phylogenetic trees used to derive $\lambda_{DR}$, $\lambda_{ND}$ and each of the 100 trees used to derive $\lambda_{BAMM}$ and $\mu_{BAMM}$. In each model we used the unique response variables and phylogenetic tree correlation structure. Specifically, for models using tip-rate metrics ($\lambda_{DR}$, $\lambda_{ND}$) we estimated the phylogenetic signal --- Pagel's $\lambda$ [@Pagel_1999] --- using the ``corPagel`` function in the ``ape`` package [@ape_2004] independently for each of the 1,000 trees/models. Alternatively, for models using speciation and extinction estimates derived using BAMM ($\lambda_{BAMM}$ and $\mu_{BAMM}$) we found $\lambda$ was consistently estimated at 1 and hence assumed Brownian motion (using the ``corBrownian`` function) to estimate the correlation structure. This method enabled us to present model estimates for an MCC tree alongside 1,000/100 trees from the posterior distribution of trees to account for phylogenetic uncertainty. This approach was repeated on three datasets corresponding to each measure of sexual selection: dichromatism derived from RGB values of images (*n* = 5,812); dichromatism from spectrophotometry (*n* = 581) and the multivariate measure of male-biased sexual selection (*n* = 2,465).  

Finally, using the subset of species with measurements of male-biased sexual selection, we conducted a phylogenetic path analysis using the phylopath ``R`` package [@Wouter_2018]. The phylogenetic path analysis was used to assess causal paths *between* variables not able to be modelled within the univariate response of PGLS. That is, a phylogenetic path analysis allowed us to model relationships between the predictor variables used in our PGLS analysis as we anticipate environmental variability, sexual dichromatism/selection, and range size to have effects on each other and not just on speciation rate. To minimise path complexity we used temperature seasonality (BIO4) as the single measure for environmental variability, $\lambda_{DR}$ as the single measure of speciation and the tip-rates from the MCC tree. Further details of the path analysis, including our rationale for each path's directions, can be found within the \href{https://justincally.github.io/SexualSelection_Speciation/}{ESM} along with all other analyses and the relevant ``R`` code to reproduce results.  


\newpage\phantomsection

# Acknowledgements

We would like to acknowledge Adnan Moussalli for his assistance in conducting BAMM runs across 100 phylogenetic trees. **Any others?**

\newpage\phantomsection

# References
<div id="refs"></div>
