---
title: Male-biased sexual selection, but not sexual dichromatism, predicts speciation in birds
author:
- Justin G. Cally*\textsuperscript{§}, Devi Stuart-Fox\textsuperscript{§}, Luke Holman\textsuperscript{§} and Iliana Medina Guzmán\textsuperscript{§}
- ~
- '*\textit{justin.g.cally@gmail.com}'
bibliography: References/SS_Extinction.bib
output:
  pdf_document: default
  html_document: default
  word_document:
    pandoc_args: --smart
header-includes: \usepackage{microtype} \usepackage[all]{hypcap} \usepackage{amsmath}
  \usepackage{booktabs} \usepackage{caption} \usepackage[labelfont=bf]{caption} \usepackage{titling}
  \pretitle{\begin{flushleft}\LARGE} \posttitle{\par\end{flushleft}\vskip 0.5em} \preauthor{\begin{flushleft}\large
  \lineskip 0.5em} \postauthor{\par\end{flushleft}} \predate{\begin{flushleft}\large}
  \postdate{\par\end{flushleft}} \usepackage{fancyhdr} \pagestyle{fancy} \fancyhead[LO,LE]{\textsl{\leftmark}}
  \rhead[]{Sexual selection predicts speciation} \usepackage[noabbrev,capitalise]{cleveref}
  \usepackage{titlefoot} \usepackage{amssymb} \usepackage{rotating} \usepackage{lineno}
  \linenumbers \usepackage{setspace}\onehalfspacing \usepackage[font={small}]{caption}
  \usepackage{epigraph} \setlength\epigraphwidth{5.25in} \setlength\epigraphrule{0pt}
  \setlength\beforeepigraphskip{1\baselineskip} \setlength\afterepigraphskip{2\baselineskip}
  \renewcommand*{\textflush}{flushright} \renewcommand*{\epigraphsize}{\footnotesize\itshape}
  \usepackage{hyperref}\hypersetup{colorlinks=true, linkcolor=blue, filecolor=blue, urlcolor=blue}
  \raggedbottom
csl: References/evolution.csl
abstract: 'Many theories related to sexual selection predict that it shapes phylogenetic diversity by altering speciation or extinction rates. The predicted effects on diversity are often contradictory; for example, sexual selection might promote speciation by creating reproductive isolation, or hinder it by selecting for traits that facilitate gene flow. Similarly, sexual selection might precipitate extinction by favouring competitive phenotypes with poor survival, or stave it off by helping populations shed deleterious mutations. Here, we investigate the relationship between sexual selection and rates of speciation and extinction in passerine birds. We use two measures of sexual selection -- sexual dichromatism (n = 5,812 species) and a multivariate measure of male-biased sexual selection (sexual dimorphism, polygyny and paternal care; n = 2,465) -- as well as three distinct measures of speciation ($\lambda_{DR}$, $\lambda_{ND}$, $\lambda_{BAMM}$), and one measure of extinction ($\mu_{BAMM}$). We also tested whether the effects of sexual selection is contingent on ecological variables such as spatiotemporal temperature variation, primary productivity, and range size. We find that male-biased sexual selection but not sexual dichromatism predicts speciation. Additionally, we find that birds with smaller ranges have higher speciation rates; although the direction of causality is unclear. \vspace{5mm} \par\noindent \textbf{Keywords:} Speciation rate, Comparative analysis, Plumage dichromatism, Range size, Extinction rate.'
---
\maketitle\unmarkedfntext{\textsuperscript{§}School of BioSciences, The University of Melbourne, Victoria, Australia.}

\newpage

#Introduction

Selection pressures are the main engine of speciation. As populations diverge they accumulate genetic and phenotypic changes that ultimately erect barriers against gene flow [@Presgraves_2010; *but see* @Shaw_2011]. In this view, populations will speciate and adapt more readily to new and different environments if selection is strong and/or persistant. Hence, the rate at which speciation occurs is likely dependent on both the population's response to selection (adaptation) and the potential for divergent phenotypic traits to evolve [*e.g.* morphology or colour @Hugall_2012; @Rabosky_morph_2013]. Sexual selection affects a diverse range of phenotypic traits important to population growth and persistance [@Cally_in_review], such as reproductive success or viability, as well as the evolution of ornaments involved in mating displays or weapons used in male-male competition [@McCullough_2016]. Sexual selection is therefore hypothesised to be a key driver of diversification, via its effects on adaptation, speciation and extinction.

Sexual selection results from competition for matings, fertilisations, or associated resources, and is typically stronger in males than females [@Fromhage_2016; @Janicke_2016; @Kokko_Jennions2008]. Sexual selection has both positive and negative consequences for 'population fitness', i.e. the average absolute fitness of individuals in the population [e.g. @Kokko_Brooks_2003; @Whitlock_Agrawal_2009; @Holman_Kokko_2013]. For example, sexual selection can elevate population fitness by helping to purge deleterious mutations [@Agrawal_2001; @Siller_2001] and fix beneficial ones [@Whitlock_2000], which should mitigate the risk of extinction due to mutation accumulation or a failure to adapte to changing environments. However, sexual selection does not always favour the evolution of traits that benefit the population...

this positive correlation is not ubiquitous; indeed sexual selection frequently favours traits having negative pleiotropic effects on female fitness [@Berger_2014; @Bonduriansky_Chenoweth_2009; @Pennell_2013; @Pischedda_2006]. For instance, in species with high levels of sexual selection, mating success becomes more variable and uncertain; thus individuals must invest heavily in costly weaponry and sexual signals to increase their chances of successfully reproducing. Such high investment, may trade off against strategies that would improve offspring fitness (*e.g.* parental care). This is a costly consequence of sexual selection that affects persistence, adaptation and extinction [@Kokko_Brooks_2003].  

Alongside changes to fitness, sexual selection has been proposed to facilitate speciation through the evolution of divergent signals/ornaments associated with improved mating success [@Lande_1981; @Lande_1982]. For instance, in antbirds (Thamnophilidae), genera with complex songs and striking dichromatism, are more species rich [@Seddon_2008]. Under this model of speciation, divergent sexual signals in one sex (usually males) co-evolve with divergent preferences for those signals in the opposite sex, leading to behavioural reproductive isolation [@Safran_2013]. Concurrently, sexual selection can increase the extent to which populations diverge by enlarging the phenotypic space diverging species can evolve into. These predictions emerge as sexual selection may increase genetic diversity as a result of trade-offs between naturally- and sexually-selected traits or trade-offs under intra-locus sexual conflict between male and female trait expressions [@Lorch_2003; @Bonduriansky_2011; @Radwan_2016]. However, the genetic architecture (*per se* heritability) of fitness and sexually selected traits may vary due to different sex determination systems across taxa. In male homogametic species (ZZ/ZW or ZZ/ZO) --- such as birds --- males are predicted to have increased heritability of male-specific genotypes on the Z chromosome associated with mating success: such as elaborate ornamentation or plumage colouration [@Hastings_1994; @Reeve_2003]. If fitness and associated mating traits are more heritable in birds we might expect bird populations experiencing stronger sexual selection to have increased adaptation and speciation rates compared to male heterogametic taxa.  

Importantly, the effects of sexual selection on adaptation and speciation may depend on environmental conditions. Both theoretical and empirical studies suggest that under stressful/changing environments, sexual selection may have greater fitness benefits than under benign environments. Stressful environments strengthen the positive correlation between male mating success and female fitness, reducing the burden of negative pleiotropic effects [@Berger_2014; @Connallon_Hall_2016; @Long_2012; @Martinossi-Allibert_Savković_2017]. Conversely, benign or stable environments ensure consistent selection, preferentially eroding genetic variation at sexually concordant loci (*i.e.* loci where the optimum genotype is equivelant for both sexes). In this situation, genetic variation remains disproportionately at sexually antagonistic loci; causing displacement of male and female traits from their optimum. It follows from these predictions that populations with stronger sexual selection would have increased fitness and adaptive benefits, allowing them to adapt to novel environments [*reviewed in* @Candolin_2008]. In certain circumstances, sexual selection will reinforce locally adaptated phenotypes through mate choice on phenotypes that effectively advertise quality in a specific ecological context [@Boughman_2002; @Maan_2011]. Additionally, if mate choice operates on both sexes --- or there is a correlation in trait values between a pair --- assortative mating is likely to speed-up the evolution of divergent mating signals [@Lande_1981]. In several bird taxa, beak morphology is a trait that arose under natural selection and is now a trait under sexual selection [a.k.a. "magic traits"; @Servedio_2011]. In Darwin's finches (*Geospiza fortis*) divergent beak morphology is an adaptation to local food availability that has been maintained through assortative mating [@Huber_2007]. Therefore, strong sexual selection and strong natural selection --- such as environmental change over space and time --- may work synergestically to increase speciation rates. 

<!-- Alternatively, sexual selection may interact with natural selection in opposing directions when environmental conditions modify the sexually selected signal, such as turbid waters that reduce the signal efficacy in sticklebacks [@Wong_2007; @Candolin_2007]. In this conflicting view, changing environments may limit the divergence of sexually selected traits and consequently reduce speciation rate.   -->

Birds are notorious for the variety of ornaments that have evolved in response to sexual selection, such as plumage colour, size dimorphism, complex courtship rituals and male song [@Gontard_1999]. The association between sexual selection and speciation has been investigated previously in birds using macroevolutionary approaches. A meta-analysis of 64 effect sizes from 20 studies found a small, but significant positive association between sexual selection and speciation across a wide range of taxa [@Kraaijeveld_2011]. Within birds, they found a positive association but much lower than that for insects and fish. However, there was large variation in effect sizes due to variation in the measures of sexual selection used and diversification proxies (*e.g.* species/subspecies richness *vs* rate estimates). Contrary to this, @Huang_2014 found no association between sexual dichromatism and speciation using tip-rate estimates from a genetic-only phylogeny [@Jetz_2012] and sexual dichromatism data from a limited spectrophotometry dataset [*n* = 918; @Armenta_2008]; similarly @Cooney_2017 found no effect of sexual dichromatism on diversification rates when using 1,306 pairs of species and human estimates of dichromatism. Given methodological advancements in tip-rate estimates [@Rabosky_diversification_2018], the association between sexual selection and speciation is worth revisiting in order to overcome previous limitations. Firstly, the strength of sexual selection in macroevolutionary studies is often estimated using measures of sexual dimorphism or dichromatism; but these are often partial measures of sexual selection and may not account for the true variation in sexual selection across taxa. Secondly, until recently, studies on the association between sexual selection and speciation have largely ignored the contribution and interaction with environmental variables to explain variation in speciation rates. Thirdly, many studies use incomplete taxon sampling, with family-level analysis restricted to well sampled avian clades [@Seddon_2008; @Huang_2014].Fourthly, phylogenetic uncertainty in the avian tree [@Jetz_2012; *but see* @Rubolini_2015] and uncertainty in tip-rate measures of speciation such as the diversification rate statistic ($\lambda_{DR}$) or node density ($\lambda_{ND}$) [@Rabosky_diversification_2018] as well as speciation and extinction tip-rates from models using BAMM (Bayesian Analysis of Macroevolutionary Mixtures) [*see*, @Beaulieu_2015; @Rabosky_Extinction_2016; @Moore_2016; @Rabosky_BAMM_flawed_2017] continue to plague efforts to identify drivers of speciation and extinction.  

Here, we perform a macroevolutionary analysis of the relationship between sexual selection and speciation or extinction in passerine birds (Order: Passeriformes), arguably the largest group for which there exists comprehensive data. We build on these previous studies by using published datasets of sexual dichromatism measured from images [*n* = 5,812; @Dale_2015] alongside smaller datasets of sexual dichromatism measured from spectrophotometry [*n* = 581; @Armenta_2008] and a composite measure of male-biased sexual selection [*n* = 2,465; @Dale_2015]. We assess the relationship between sexual selection, environmental variability and their interaction with three tip-rate measures of speciation and one measure of extinction ($\lambda_{DR}$, $\lambda_{ND}$, $\lambda_{BAMM}$ and $\mu_{BAMM}$). Using expert range maps and bioclimatic variables we are able to investigate whether the effect of sexual selection on speciation is dependent on range size, seasonal variation in temperature, spatial temperature variation (across a species’ range), long-term variation in temperature between now and the last inter-glacial (LIG) as well net primary productivity (NPP).  


#Materials and methods

We examined the effect of sexual selection on speciation and extinction rate in 97 % of passerines (*n* = 5,812 species; 58 % of all birds). Specifically, we (*i*) compiled datasets for sexual dichromatism/selection strength and environmental variability, (*ii*) obtained estimates of speciation and extinction rates across passerines, and (*iii*) conducted phylogenetic generalized least-squares (PGLS) regressions. Analyses are documented with reproducible code in the \href{https://justincally.github.io/SexualSelection_Speciation/}{electronic supplementary material (ESM)}.  

##Compiling data for sexual selection and environmental stress

###Sexual dichromatism

We used a previously published measure of sexual selection for 5,983 species of passerines [@Dale_2015]. Briefly, @Dale_2015 obtained sex-specific RGB (red, green and blue) values across six body patches (nape, crown, forhead, throat, upper breast and lower breast) from _Handbook of the Birds of the World_ (volumes 8–16) [@delhoyo2011]. The relative contribution of male and female RGB colour values were averaged across body patches and provide 'male-like' and 'female-like' plumage scores. Here we use the absolute difference between male and female plumage scores as an estimate of sexual dichromatism. Additionally, we used a measure of dichromatism from spectral data, used to estimate colour distance in avian colour space [@Armenta_2008]. These measurements include variation in the ultraviolet and bird-visible range and --- unlike the RGB measures --- are sourced from taxonomic samples (as opposed to colour drawings). However, this spectrophotometry data is not as extensive as the RGB measures; with only 581 passerine species available for this analysis. While there is a correlation between these two measures, there is residual variation ($r = 0.79$; \href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Figure S9}).  

###Male-biased sexual selection

Sexual dichromatism is a widely used indicator of sexual selection in birds [*e.g.*, @Barraclough_1995; @Seddon_2013; @Morrow_Speciation_2003; @Owens_1999; @Huang_2014], but only partially captures variation in the strength of sexual selection across taxa. Therefore, we also use an existing dataset [@Dale_2015] of male-biased sexual selection based on the first component of a phylogenetic principle component analysis (PPCA) of three characteristics associated with sexual selection (sexual size dimorphism, social polygyny and [lack of] paternal care). This measure of male-biased sexual selection is available for only 2,465 species and is weakly correlated with the absolute values of sexual dichromatism using RGB measures ($r = 0.34$; \href{https://justincally.github.io/SexualSelection_Speciation/#analysis_using_male-biased_measure_of_sexual_selection}{Figure S11}).  

###Environmental variables 

We obtained estimates of species range size using expert range maps [@birdlife_2017]. Because of taxanomic changes to 1,230 species in the _Birdlife_ database [@delhoyo_2016] we manually matched these taxa with the names used in the sexual dichromatism dataset [@Dale_2015]. From these distributions we obtained estimates of climatic conditions that each species is exposed to. That is, we took 1,000 random point samples in each range and extracted 19 present-day bioclimatic variables (representing a variety of biologically relevant annual trends in temperature and precipitation) with 30 seconds (~1 km^2^) spatial resolution [@Fick_2017]. From these values we obtained means and standard deviations for each species. Using the same spatial sampling we extracted means and standard deviations of bioclimatic variables from the paleoclimate during the last interglacial (LIG; 120,000 - 140,000 years ago) [@Otto-Bliesner_2006]. Furthermore, to estimate variability in the energy available to species we obtained the mean and standard deviation of net primary productivity (NPP) values between 2000 - 2015 across each species distribution. Estimates of NPP had 30 second resolution and were obtained through MODIS (Moderate Resolution Imaging Spectroradiometer) primary production products stage 3 (MOD17A3) [@Zhao_2005]. Using this data, which we provide as a potentially useful data resource (see ESM), we generated five predictors of speciation associated with different patterns in environmental variability (see below).  

###Generating biologically relevent predictors for environmental variation

Using the extracted environmental variables from each species range size we developed biologically meaningful predictors of environmental variation/stress relating to (*i*) seasonal climate variation, (*ii*) spatial climate variation and (*iii*) long-term climate variation. To obtain seasonal climate variation we used mean values of temperature seasonality (BIO4) for each range. To estimate levels of spatial environmental variation a species may endure we used the first principle component (PC1) from a PCA on standard deviations from all bioclimatic variables, excluding temperature (BIO4) and precipitation seasonality (BIO15). PC1 was heavily loaded towards bioclimatic variables relating to temperature, thus PC1 reflects the variation in temperature across a species' range (\href{https://justincally.github.io/SexualSelection_Speciation/#generating_biologically_relevent_predictors}{Table S1}). Given that species range is a potentially informative predictor of speciation and extinction we controlled for the correlation between spatial variation and range size --- where larger ranges have larger variation in PC1 --- by taking the residuals of a fitted general additive model (GAM; \href{https://justincally.github.io/SexualSelection_Speciation/#generating_biologically_relevent_predictors}{Figure S1}). To obtain long-term variation in climates for each species range we take the first principal component of the absolute difference in the bioclimatic variables between the LIG and current values. Similarly to spatial variation, the long-term climate variation is primarily loaded to temperature differences between the LIG and current climates (\href{https://justincally.github.io/SexualSelection_Speciation/#long_term_climate_variability_(lig_anomaly)}{Table S2, Figure S2}).The five predictors of environmental variability are not strongly correlated (\href{https://justincally.github.io/SexualSelection_Speciation/#correlations_between_environmental_predictors}{Figure S3}). Details and code to generate these predictors can be found within the \href{https://justincally.github.io/SexualSelection_Speciation/}{ESM}.  

##Estimating extinction and speciation. 

Phylogenetic information was obtained from www.birdtree.org [@Jetz_2012]. We used a maximum clade credibility (MCC) tree from 2,500 samples of the posterior distribution that were subset to the passerine bird order (*n* = 5,965) as the main phylogentic tree in our comparative analysis. Additionally, a random draw of 100 full trees (including species without genetic data) from the posterior distribution of phylogenetic trees was used for diversification analyses using tip-rate measures and BAMM [@Rabosky_2014]. These trees used a 'Hackett backbone' [@Hackett_2008] and were constructed using the a pure birth (Yule) model. We calculated three different tip-rate metrics of speciation and one of extinction across all trees.  

Firstly, we obtained two tip-rate metrics of speciation using statistics derived from the properties of the nodes and branches along root-to-tip paths of the phylogeny. Node density (ND) is a simple statistic calculating the density of nodes from the phylogenetic root to the tip, while the log-transformed equal splits (logES), also known as diversification rate (DR) [*e.g.*, @Jetz_2012; @quintero_2018; @Rabosky_fish_2018], is derived from the sum of edge lengths branching from a node, with each more basal node having the sum of lengths down-weighted. Studies have suggested that DR and ND (henceforth referred to as $\lambda_{DR}$ and $\lambda_{ND}$) are more reflective estimates of speciation than diversification [@Belmaker_2015; @Rabosky_diversification_2018]. Therefore, $\lambda_{DR}$ is a measure of speciation rate more heavily weighted to recent speciation events and $\lambda_{ND}$ is a measure of speciation across the root-to-tip path. These tip-rate measures are alternatives to state-dependent diversification models such as Quantitative State Speciation-Extinction (QuaSSE). But, based on previous simulation studies $\lambda_{DR}$ and $\lambda_{ND}$ are robust and intuitive measures that provide high power and low false discovery rate with large phylogenies when incorporated into Phylogenetic Generalized Least Squares (PGLS) models [@Harvey_essim_2017].  

Secondly, we used BAMM to model the dynamics of speciation and extinction across the 100 phylogenetic trees [@Rabosky_2014]. This software uses a Bayesian approach (reversible-jump Markov Chain Monte Carlo) to generate a probability distribution of evolutionary rate-shift configurations with variable speciation and extinction rates. Importantly, these models provide tip-rate estimates of speciation and extinction rate. The parameters of the 100 BAMM runs are detailed in full in the \href{https://justincally.github.io/SexualSelection_Speciation/}{ESM}; briefly we used a time-variable model with 100 expected number of shifts and prior rates set from the initial speciation and extinction values using the ``BAMMtools`` R package [@bammtools_2014]. Each BAMM model (one MCC and 100 random draws of the posterior) was run for 100 million generations, and given the computationally intensive nature of BAMM, runs were conducted across multiple CPU's. Each run of BAMM reached convergence with effective sample size (ESS) of MCMC (Markov Chain Monte Carlo) samples surpassing 200 (an arbitrary value, above which posterior distributions can often be accurately inferred) for the key model parameters of log-likelihood and number of rate shifts (\href{https://justincally.github.io/SexualSelection_Speciation/#bamm_measures_of_speciation_and_extinction}{Table S3}, \href{https://justincally.github.io/SexualSelection_Speciation/#bamm_measures_of_speciation_and_extinction}{Table S4}). Further details of BAMM parameters and output are available in the \href{https://justincally.github.io/SexualSelection_Speciation/}{ESM}, with tip-rate means and variances provided. Additionally, given the variability in BAMM estimates, we also provide some analysis of BAMM shift configurations and tip-rate estimates from our run on the MCC tree and within a BAMM run on the MCC tree from a genetic-only phylogeny across all birds [@Harvey_2017]. All analyses were conducted on log-rates.   

##Statistical analysis

###Phylogenetic camparative analysis

To test the association between speciation/extinction and sexual selection, environmental variability and their interaction, we used phylogenetic least squares (PGLS) models in the ``nlme`` package [@nlme_2018]. We began by estimating the phylogenetic signal --- Pagel's $\lambda$ [@Pagel_1999] --- using the ``corPagel`` function in the ``ape`` package [@ape_2004] on the MCC tree. The estimate of $\lambda$ was then fixed for model selection, which was conducted on the same MCC tree derived from 2,500 draws of the posterior distribution [@Jetz_2012]. Model selection used either $\lambda_{DR}$, $\lambda_{ND}$, $\lambda_{BAMM}$ or $\mu_{BAMM}$ tip-rate estimates from the MCC tree as the response variable. For $\lambda_{BAMM}$ and $\mu_{BAMM}$ we were also able to use model weights sourced from the inverse of the variance of tip-rates for a given species from the posterior distribution (*n* = 1,000). Model weights thus reflect the degree of precision to which each species tip-rate is measured in BAMM. Using model selection we only compared interaction terms between a measure of sexual selection (sexual dichromatism or male-biased sexual selection) and environmental measures. That is, we fixed the individual predictors of: dichromatism/male-biased sexual selection measures, log-transformed range size, seasonal temperature variation, spatial temperature variation, long-term temperature variation and NPP while comparing 32 models with different combinations of interactions (including none). Model selection was done in ``MuMIn`` using the ``dredge`` function [@MuMIn_2017]. Using the terms from the top-ranking model (lowest AICc), we ran the equivalent model for each of the 100 phylogenetic trees used to derive $\lambda_{DR}$, $\lambda_{ND}$, $\lambda_{BAMM}$ and $\mu_{BAMM}$, using the unique response variables and phylogenetic tree correlation structure in each model. This method enabled us to present model estimates for an MCC tree alongside 100 trees from the posterior distribution of trees to account for phylogenetic uncertainty. This approach was repeated on three datasets corresponding to each measure of sexual selection: dichromatism derived from RGB values of images (*n* = 5,812); dichromatism from spectrophotometry (*n* = 581) and the multivariate measure of male-biased sexual selection (*n* = 2,465).  

Finally, using data subsetted for species with measurements of male-biased sexual selection, we conducted a phylogenetic path analysis using the phylopath ``R`` package [@Wouter_2018]. The phylogenetic path analysis was used to assess causal paths between variables not able to be modelled within the univariate response of PGLS. That is, a phylogenetic path analysis allowed us to model relationships between the predictor variables used in our PGLS analysis as we anticipate environmental variability, sexual dichromatism/selection and range size to have effects on each other and not just on speciation rate. To minimise path complexity we use temperature seasonality (BIO4) as the single measure for environmental variability and use $\lambda_{DR}$ as the single measure of speciation. The phylogenetic path analysis used tip-rates and correlation structure from the MCC tree. Further details of the path analysis including reasons for path directions can be found within the \href{https://justincally.github.io/SexualSelection_Speciation/}{ESM} along with all other analyses and the relevant ``R`` code to reproduce results.  

```{r, echo=FALSE}
MCC.DR.top <- readRDS('data/MCC.DR.top.rds')
MCC.ND.top <- readRDS('data/MCC.ND.top.rds')
MCC.Lambda.top <- readRDS('data/MCC.Lambda.top.rds')
MCC.Mu.top <- readRDS('data/MCC.Mu.top.rds')

#hpds
hpd.DR.top <- readRDS('data/hpd.DR.top.rds')
hpd.ND.top <- readRDS('data/hpd.ND.top.rds')
Armenta.hpd.DR.top <- readRDS('data/Armenta.hpd.DR.top.rds')

#Male bias SS
Subset.MCC.DR.top <- readRDS('data/Subset.MCC.DR.top.rds')
Subset.MCC.ND.top <- readRDS('data/Subset.MCC.ND.top.rds')
Subset.MCC.Lambda.top <- readRDS('data/Subset.MCC.Lambda.top.rds')
Subset.hpd.DR.top <- readRDS('data/Subset.hpd.DR.top.rds')
Subset.hpd.ND.top <- readRDS('data/Subset.hpd.ND.top.rds')
Subset.hpd.Lambda.top <- readRDS('data/Subset.hpd.Lambda.top.rds')
MCC.BAMM.df <- readRDS('data/MCC.BAMM.df.rds')

#path analysis
best_model <- readRDS('data/path_model.rds')
```
#Results

##Effects of sexual dichromatism/selection on speciation are not dependent on environmental variability

PGLS models with interaction terms between each measure of sexual dichromatism/selection and the five measures of environmental variability (seasonal temperature variation, log-range size, long-term temperature variation, spatial temperature variation and NPP) were included in model selection. However, no interaction terms were significant or present in the top models ($\delta$ AICc > 4) for any measure of speciation ($\lambda_{DR}$, $\lambda_{ND}$, $\lambda_{BAMM}$) or sexual selection (RGB values, spectrophotometry and male-biased sexual selection; $\delta$ AICc > 4; \href{https://justincally.github.io/SexualSelection_Speciation/#pgls_models_on_dr_and_nd}{Table S5}, \href{https://justincally.github.io/SexualSelection_Speciation/#pgls_models_on_bamm_estimates}{Table S6}, \href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Table S10}, \href{https://justincally.github.io/SexualSelection_Speciation/#analysis_using_male-biased_measure_of_sexual_selection}{Table S13}). Thus we found no evidence that the effect of sexual selection on speciation is dependent on our measures of environmental variation. Furthermore, we found no evidence that these environmental factors (seasonal temperature variation, long-term temperature variation, spatial temperature variation and NPP) predict speciation independently from sexual dichromatism/selection (\autoref{model_results}, \href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Figure S10}).   

##No evidence that sexual dichromatism affects speciation

We found no evidence that species with increased sexual dichromatism have higher or lower rates of speciation. Using three response measures of speciation ($\lambda_{DR}$, $\lambda_{ND}$, $\lambda_{BAMM}$), the effect of sexual dichromatism was not significant in any PGLS model based on tip-rate estimates and correlation structures from the MCC tree. Specifically, sexual dichromatism showed no association with $\lambda_{DR}$ ($\beta$ = `r formatC(MCC.DR.top[["coefficients"]][["SDi"]], format = "e", digits = 3)`, p = `r round(anova(MCC.DR.top)[["SDi","p-value"]], digits = 3)`; \autoref{model_results}a, \autoref{Speciation_Figure}a) or $\lambda_{ND}$ ($\beta$ = `r formatC(MCC.ND.top[["coefficients"]][["SDi"]], format = "e", digits = 3)`, p = `r round(anova(MCC.ND.top)[["SDi","p-value"]], digits = 3)`; \autoref{model_results}a). Furthermore, speciation rates from BAMM ($\lambda_{BAMM}$) were also unaffected by sexual dichromatism ($\beta$ = `r formatC(MCC.Lambda.top[["coefficients"]][["SDi"]], format = "e", digits = 3)`, p = `r round(anova(MCC.Lambda.top)[["SDi","p-value"]], digits = 3)`; \autoref{model_results}a). PGLS analyses using subsetted data (*n* = 581), where sexual dichromatism was measured using spectrophotometry [@Armenta_2008] yielded results concordant to the full data set; that is, no association between sexual dichromatism and speciation or extinction (\href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Figure S10}). Our results from MCC models are largely corroborated by model estimates from PGLS analyses of the rates and correlation structures from 100 random trees. Model estimates are normally distributed around zero when using complete taxon sampling models and RGB measures of sexual dichromatism (\autoref{model_results}a, see HPD (highest posterior density) intervals in \href{https://justincally.github.io/SexualSelection_Speciation/#pgls_model_summary}{Table S8}). For PGLS models using spectrophotometry-based measures of sexual dichromatism, the estimates from the 100 trees in the $\lambda_{DR}$ models are positively skewed (`r formatC(Armenta.hpd.DR.top$Colour.discriminability, format = "e", digits = 3)`) but normally distributed around zero for $\lambda_{ND}$ and $\lambda_{BAMM}$ (\href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Table S12}).  

##Male-biased sexual selection increases speciation

We found a significant positive association between male-biased sexual selection (*n* = 2,465) and $\lambda_{DR}$ ($\beta$ = `r formatC(Subset.MCC.DR.top[["coefficients"]][["Sexual_selection_ppca"]], format = "e", digits = 3)`, p = `r round(anova(Subset.MCC.DR.top)[["Sexual_selection_ppca","p-value"]], digits = 3)`; \autoref{model_results}b). However, this associate was not significant for the other two measures of speciation rate ($\lambda_{ND}$: $\beta$ = `r formatC(Subset.MCC.ND.top[["coefficients"]][["Sexual_selection_ppca"]], format = "e", digits = 3)`, p = `r round(anova(Subset.MCC.ND.top)[["Sexual_selection_ppca","p-value"]], digits = 3)`; $\lambda_{BAMM}$: $\beta$ = `r formatC(Subset.MCC.Lambda.top[["coefficients"]][["Sexual_selection_ppca"]], format = "e", digits = 3)`, p = `r round(anova(Subset.MCC.Lambda.top)[["Sexual_selection_ppca","p-value"]], digits = 3)`; \autoref{model_results}b). The distribution of estimates from PGLS models on 100 random trees was similar to the estimate from an MCC tree: among the 100 tress there was a positive association between sexual selection and $\lambda_{DR}$ (HPD Interval = `r formatC(Subset.hpd.DR.top$Sexual_selection_ppca, format = "e", digits = 3)`), and a smaller positive association between sexual selection and $\lambda_{ND}$ (HPD Interval = `r formatC(Subset.hpd.ND.top$Sexual_selection_ppca, format = "e", digits = 3)`; ) as well as $\lambda_{BAMM}$ (HPD Interval = `r formatC(Subset.hpd.Lambda.top$Sexual_selection_ppca, format = "e", digits = 3)`). Complete HPD intervals for models using male-bias sexual selection PPCA as a predictor can be found within \href{https://justincally.github.io/SexualSelection_Speciation/#analysis_using_male-biased_measure_of_sexual_selection}{Table S15}.  


##Species with smaller ranges have increased rates of speciation

Based on $\lambda_{DR}$ and $\lambda_{ND}$ tip-rate metrics of speciation we found a negative association between range size and speciation; that is, species with smaller ranges show marginally higher values for $\lambda_{DR}$ and $\lambda_{ND}$. This negative association was small but significant for models using the MCC tree ($\lambda_{DR}$: $\beta$ = `r formatC(MCC.DR.top[["coefficients"]][["log(range.size.m2)"]], format = "e", digits = 3)`, p = `r round(anova(MCC.DR.top)[["log(range.size.m2)","p-value"]], digits = 3)`; $\lambda_{ND}$: $\beta$ = `r formatC(MCC.ND.top[["coefficients"]][["log(range.size.m2)"]], format = "e", digits = 3)`, p = `r round(anova(MCC.ND.top)[["log(range.size.m2)","p-value"]], digits = 3)`; \autoref{model_results}a, \autoref{Speciation_Figure}). This association was also evident across the estimates from models using the 100 trees ($\lambda_{DR}$: HPD Interval = `r formatC(hpd.DR.top[[2]], format = "e", digits = 3)`; $\lambda_{ND}$: HPD Interval = `r formatC(hpd.ND.top[[2]], format = "e", digits = 3)`; \autoref{model_results}a). Subsetted models with reduced sample size and different measures of sexual selection --- but the same measure of range size --- showed variable evidence that range size is negatively associated with speciation. Range size significantly predicted $\lambda_{DR}$ (\autoref{model_results}b) using data subsetted for male-biased sexual selection (*n* = 2,465) but not $\lambda_{ND}$ or $\lambda_{BAMM}$. Model using data subsetted for spectrophotometry-based dichromatism (*n* = 581) gave non-significant estimates for the effect of range size on all measures of speciation (\href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Figure S10}, \href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Table S11}, \href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Table S12}). Because the range size dataset is the same across the three data subsets we draw our conclusions from the models with highest power using near-complete taxon sampling (*n* = 5,812).   

##Phylogenetic path analysis

Using a phylogenetic path analysis, we found multiple significant paths between variables used in the PGLS (\autoref{Path_Analysis}; \href{https://justincally.github.io/SexualSelection_Speciation/#phylogenetic_path_analysis}{Figure S13}). Notably, environmental variability (temperature seasonality) directly affected sexual dichromatism ($\beta$ = `r round(best_model[["coef"]][1,4], digits = 2)`) and the path from male-biased sexual selection to sexual dichromatism was relatively weak, ($\beta$ = `r round(best_model[["coef"]][2,4], digits = 2)`), despite dichromatism being widely used as an indicator of the strength of sexual selection. Additionally, the large direct effect of temperature seasonality on range size ($\beta$ = `r round(best_model[["coef"]][1,3], digits = 2)`) suggests an indirect effect of temperature seasonality on $\lambda_{DR}$ ($\beta$ = `r round(best_model[["coef"]][1,3]*best_model[["coef"]][3,5], digits = 2)`; \autoref{Path_Analysis}), given the negative we identified between $\lambda_{DR}$ and range size in PGLS models.   

##Extinction rate

We found no evidence that extinction ($\mu_{BAMM}$) was impacted by the extent of sexual dichromatism for full-taxon sampling ($\beta$ = `r formatC(MCC.Mu.top[["coefficients"]][["SDi"]], format = "e", digits = 3)`, p = `r round(anova(MCC.Mu.top)[["SDi","p-value"]], digits = 3)`; \autoref{model_results}a), nor spectrophotometry-based measures of sexual dichromatism (\href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Figure S10}, \href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Table S11}, \href{https://justincally.github.io/SexualSelection_Speciation/#subsetted_analysis_with_spectrophotometry_data}{Table S12}) or male-biased sexual selection (\autoref{model_results}b, \href{https://justincally.github.io/SexualSelection_Speciation/#analysis_using_male-biased_measure_of_sexual_selection}{Table S14}, \href{https://justincally.github.io/SexualSelection_Speciation/#analysis_using_male-biased_measure_of_sexual_selection}{Table S15}).  


##Variability across trees and methods

We tested our hypothesis that sexual selection is associated with speciation using several methods and across 100 trees drawn from the post burn-in posterior [@Jetz_2012]. We used a range of methods to overcome uncertainty in the power and precision of various tip-rate estimates as well as the variation between trees. We found that that the tip-rate estimates across the 100 trees were quite variable for both $\lambda_{DR}$ and $\lambda_{BAMM}$ (\href{https://justincally.github.io/SexualSelection_Speciation/#additional_figures_and_tables}{Figure S14}). Despite this, tip-rate estimates of speciation from the two methods were moderately correlated across the 100 trees ($r = 0.75$) and for the MCC tree ($r = 0.68$; \href{https://justincally.github.io/SexualSelection_Speciation/#additional_figures_and_tables}{Figure S15}). However, in comparison to $\lambda_{DR}$, the value of $\lambda_{BAMM}$ was the _mean_ drawn from a posterior distribution (*n* = 1,000) of BAMM generations, thus estimates of $\lambda_{BAMM}$ (and $\mu_{BAMM}$) have an added level of variation. To account for this variation, weights (using the inverse of the variance) were used for the PGLS models. From 1000 posterior samples of the MCC BAMM run the coefficient of variation (*CV*) for all log-rates of $\lambda_{BAMM}$ was relatively low (*mean CV* = `r round(mean(MCC.BAMM.df$CV.lambda), digits = 2)`, *median CV* = `r round(median(MCC.BAMM.df$CV.lambda), digits = 2)` ; *see* \href{https://justincally.github.io/SexualSelection_Speciation/#bamm_measures_of_speciation_and_extinction}{Figures S5} and \href{https://justincally.github.io/SexualSelection_Speciation/#bamm_measures_of_speciation_and_extinction}{Figure S7}). Despite the convergence of the BAMM model in all runs --- where effective sample sizes of the number of shifts and log-likelihood were all greater than 200 (\href{https://justincally.github.io/SexualSelection_Speciation/#bamm_measures_of_speciation_and_extinction}{Table S3}, \href{https://justincally.github.io/SexualSelection_Speciation/#bamm_measures_of_speciation_and_extinction}{Table S4}) --- we found that the unique combinations of rate shifts across the large phylogenetic tree (*n* = 5,966 species) was high. This means that although the number of rate shifts reached convergence ($median = 59$; \href{https://justincally.github.io/SexualSelection_Speciation/#bamm_measures_of_speciation_and_extinction}{Figure S6}), the locations of the rate shifts (*i.e.* the credible shift set) across the tree are highly heterogeneous. The variability in the locations for the shift configurations is a likely source of uncertainty in downstream tip-rates used as the response variable in PGLS models. Notably, the 95 % HPD interval for model estimates using BAMM rates from 100 trees was about 20-fold the 95 % confidence intervals of the estimate from the MCC tree; whereas for $\lambda_{DR}$ and $\lambda_{ND}$ the HPD 95 % interval width was equal to or less than the MCC 95 % CI (\autoref{model_results}, \href{https://justincally.github.io/SexualSelection_Speciation/#pgls_model_summary}{Table S9}).  

![Model estimates for (**a**) PGLS analyses using sexual dichromatism (*n* = 5,812) and (**b**) PGLS analyses using measures of male-biased sexual selection (*n* = 2,465). Both datasets were used for analyses with three measures of speciation ($\lambda_{DR}$, $\lambda_{ND}$, $\lambda_{BAMM}$) and one measure of extinction ($\mu_{BAMM}$) as response variables. The numerical values for the model estimates using the MCC tree and HPD intervals of estimates from 100 random trees can be found in the ESM. Density curves are based on estimates from 100 trees and the circle below with error bars is the estimate and 95 % CIs from the MCC tree. For this figure we removed outliers from estimates coming from the 100 random trees for BAMM models in order to interpret the MCC 95 % CIs. \label{model_results}](Figures/ModelEstimates.pdf)  

![Speciation rate ($\lambda_{DR}$) across all passerine birds (*n* = 5,965) with estimates of sexual dichromatism and range size available for 5,812 of them. Across these species there was a small but significant negative association between $\lambda_{DR}$ and log-range size but no significant association between $\lambda_{DR}$ and sexual dichromatism based on RGB. $\lambda_{DR}$ are those from the MCC tree and images of birds are from the _Handbook of the Birds of the World_. Clockwise the species are: _Sporophila bouvronides_, _Geospiza magnirostris_, _Atlapetes leucopterus_, _Euphonia rufiventris_, _Euplectes franciscanus_,_Promerops gurneyi_, _Phainopepla nitens_, _Zosterops erythropleurus_, _Acrocephalus australis_, _Progne cryptoleuca_, _Mayrornis schistaceus_, _Paradisaea rubra_, _Pachycephala pectoralis_, _Malurus pulcherrimus_, _Cranioleuca curtata_, _Cercomacra manu_, _Muscisaxicola capistratus_, _Lepidothrix coeruleocapilla_. Edge colours for the terminal branch correspond to $\lambda_{DR}$ but all precluding branches have been generated for graphical purposes using ancestral character state estimation and should not be interpreted. \label{Speciation_Figure}](Figures/DRSpeciationFigure.pdf)  

![Path analysis of evolutionary and ecological variables. Arrows represent direct effects with numeric values corresponding to colours (blue = positive, red = negative). The numeric values are standardised regression slopes and the asterisks indicates that the 95 % confidence intervals of this estimate do not overlap with zero. The confidence intervals were obtained from 500 bootstrapped iterations and the data used in this analysis was subset to species with both sexual dichromatism and male-biased sexual selection measures (*n* = 2,465). \label{Path_Analysis}](Figures/Path_Analysis.pdf)  

\newpage  

#Discussion

We found no evidence that sexual dichromatism alters the rate of speciation in passerine birds independently or via interactions with environmental variability. This result is consistent across different measures of speciation ($\lambda_{DR}$, $\lambda_{ND}$ and $\lambda_{BAMM}$) and two measures of dichromatism (spectral and RGB). The results are also consistent with previous studies performed at a smaller scale [@Huang_2014; @Cooney_2017]. However, we found that when using a measure of male-biased sexual selection --- instead of sexual dichromatism --- there was a positive association with speciation, though the strength of this relationship varied across different rate estimates. Our findings suggest that the components of the composite measure of male-biased sexual selection (sexual size dimorphism, social polygyny and [lack of] paternal care) are better predictors of speciation than sexual dichromatism. No bioclimatic measures of environmental variability (temperature seasonality, long-term temperature variation and spatial temperature variation) predicted speciation, but range size was negatively associated with two measures of speciation ($\lambda_{DR}$, $\lambda_{ND}$). This suggests that species with smaller range sizes have increased speciation rate, however, small range size may be a cause or effect of elevated speciation rate and potentially even an artifact of taxonomic classification. Interestingly we found a discrepancy in the model results obtained from tip-rate statistics ($\lambda_{DR}$, $\lambda_{ND}$) and those using tip-rate estimates from a model-based approach ($\lambda_{BAMM}$); whereby BAMM produced precisely null results for most associations between predictors and speciation as well as extinction. 

The association between sexual selection and sexual dichromatism in birds is a Darwinian trope [@Darwin_1871] that allows it to be commonly used as a proxy for the strength of sexual selection in comparative studies [*e.g.*, @Barraclough_1995; @Seddon_2013; @Morrow_Speciation_2003; @Owens_1999; @Huang_2014]. Despite the association between sexual selection and sexual dichromatism in passerine birds [@Dale_2015] we find that sexual dichromatism does not predict speciation rate, whereas male-biased sexual selection does. Given our results, we suggest that sexual dichromatism may not be a robust proxy for sexual selection, and that variance in the association between dichromatism and the strength of sexual selection may obscure any relationship with speciation rate, despite the high power of our comparative study. There are several reasons why the use of sexual dichromatism as a proxy for sexual selection is problematic. Firstly, ecological pressures could drive sexual dichromatism in the absence of mate choice if sex-specific niches provide opportunity for the evolution of sex-limited traits [@Wallace_1889; @Kottler_1980; @Slatkin_1984; @Shine_1989]. Specifically, natural selection on females may be important in explaining patterns of sexual dichromatism in birds [@Price_2014]. In fairy-wrens (*Malurus cyaneus*), female colouration has evolved in response to environmental pressures, leading to increased sexual dichromatism in regions where females are under stronger selection from predation [@Medina_2017]. Ecological impacts on sexual dichromatism are supported by our path analysis, which reveals that sexual dichromatism is positively affected by temperature seasonality (a measure of environmental variation) albeit relatively weakly. Secondly, colour is but one trait and sexual selection may drive the evolution of sex differences in a wide variety of traits used in mate choice or intrasexual competition [@Miles_2018]. And thirdly, not all plumage colouration honestly reflects mate quality. A recent meta-analysis found that converted carotenoids (but not those sourced from diet) predict mate quality through improvements in parasite resistance and reproductive success [@Weaver_2018]. Given the importance of honest signaling in sexual selection and the variability in colour production across birds, sexual dichromatism in many species may be an unreliable measure of mate quality for female birds and sexual selection for researchers.  

In-line with predictions and a previous meta-analysis [@Kraaijeveld_2011] we found that male-biased sexual selection increases speciation rate --- at least for $\lambda_{DR}$ and $\lambda_{ND}$ estimates --- but this association was not dependent on variable or stressful environments. When evolving under stressful conditions, sexually antagonistic selection is hypothesised to be weakened relative to selection that is concordant between the sexes [@Connallon_SA_2015; @Connallon_Hall_2016]. While these predictions are supported in several lab (experimental evolution) studies [@Long_2012; @Berger_2014; @Punzalan_2013], other studies have not found the association [@Delcourt_2009; @Martinossi-Allibert_Savković_2017; @Holman_Jacomb_2017]. The environmental variability predictors used here often reflected changes in climate across space and time, whereby high environmental variation would likely increase the strength of natural selection on a given species. Given that we did not detect an effect of environmental variability (by itself or as an interaction with sexual selection) we are left with several possible explanations. Firstly, the effects of sexual selection on adaptation and thus speciation may depend on the type of environmental variability the species is evolving under. Specifically, sexual antagonism may be more easily purged in environments where cyclic pressures (*e.g.* seasonality) are perpetuated; whereas when environmental variability is directional (*e.g.* long-term climatic change) sexual antagonism can remain indefinitely as a fitness burden [@Connallon_Hall_2016]. Secondly, the environmental predictors used here may not account for the key ecological forces/natural selection pressures that interact with sexual selection to drive speciation. Specifically, access to dietary resources, and the impacts of predation or parasitism are unaccounted for here: arguably these are key processes affecting sexual selection and speciation [*reviewed in* @Maan_2011]. Thirdly, it is also possible that there is no effect of environmental variability on speciation rates; at least not in the species investigated here.  

<!-- **Make it about evolvability** -->
<!-- The effects of sexual selection are complex and are expected to vary amongst taxa. Although birds have a sex determination system conducive to increased father-to-son heritability of male-specific fitness traits on the Z chromosome [@Hastings_1994; @Reeve_2003] there are counteravailing arguments suggesting that deleterious recessive alleles on the Z chromosome in males (ZZ) are less exposed to selection, thus limiting the evolvability of traits [@Charlesworth_1987; @Charlesworth_2018]. In a macro-evolutionary meta-analysis on sexual selection and speciation rate @Kraaijeveld_2011 found no significant taxon based differences across a diverse sample of vertebrates and invertebrates (fish, insects, birds, spiders, reptiles, mammals). Yet sexual selection in male homogametic taxa (birds) produced noticibly faster speciation rates than in male heterogametic taxa **Would be good to get raw data off them and do a pair-wise comparison**. The evolvability of the   -->

The most consistent finding uncovered in this comparative analysis is that smaller range sizes are associated with increased speciation rates; however reduced range size can be a cause or consequence of speciation. Intuitively, large range size should promote speciation by creating greater opportunities for geographic barriers to form [@Rosenzweig_1995]. However, birds with smaller range sizes are predicted to have lower dispersal ability. This ensues that individuals might not be able to overcome geographical barriers and maintain gene flow; which would promote reproductive isolation and speciation [@Birand_2012; @Claramunt_2012]. Several studies have used morphological measures of wing shape (Hand-wing index/ Kipp's distance) --- a proxy for dispersal ability --- as predictors of speciation and coexistence [*e.g.*, @Kennedy_2016; @Pigot_2016]. But currently, published datasets of these measurements are not available for many passerines. Alternatively, reduced range size may be a consequence of speciation. Under this view, high speciation rate may lead to smaller range sizes as niche filling by recently diverged species will suppress the expansion of newly speciated relatives. Within Himalayan songbirds, range expansions are prevented by the competition for resources by related species [@Price_2014]; this supression on range expansion is then expected to prevent future speciation events [@Rosenzweig_1995; @Weir_2011]. Unlike Himalayan songbirds, species undergoing adaptive radiation in new niches are unlikely to be limited by competition for resources from existing taxa. Across islands we expect to see a correlation between speciation and small range size because they reflect newly formed environments with empty niches. Thus, our findings may be heavily dependent on species whose range size is restricted to a single island within an archipelago (*e.g.* *Geospiza* sp.; a.k.a. Darwin's finches). One further explanation for the negative association between range size and sexual dichromatism/sexual selection is the potential bias of taxonomic classification, whereby over-splitting of species in clades with large ranges leads to increased recent phylogenetic branching as well as smaller ranges. Given the problems of determining causality and mode of speciation the reason for the negative association found here remains obscured.  

In addition to speciation, sexual selection has frequently been invoked as a driver of extinction. Sexual selection may increase extinction risk as it often leads individuals (usually males) to invest in exaggerated mating signals as opposed to traits --- such as parental care --- that elevate offspring fitness [*reviewed in* @Kokko_Brooks_2003]. Using BAMM, we found no association between extinction rate and sexual dichromatism, male-biased sexual selection or measures of environmental variability. Extinction is notoriously hard to estimate accurately [*see* @Rabosky_Extinction_2016]. It can be estimated from phylogenetic inference, fossil record, records of recent extinctions and IUCN extinction threat status. Phylogenetic methods --- like BAMM --- allow for speciation and extinction rates to be measured using moderately sized phylogenies. However, BAMM has been subject to controversy in its ability to model rate shifts and extinction rates [*see*, @Beaulieu_2015; @Rabosky_Extinction_2016; @Moore_2016; @Rabosky_BAMM_flawed_2017], and while several tip-rate estimates exist for speciation (*e.g.*, $\lambda_{DR}$ and $\lambda_{ND}$) extinction estimates are not as easily obtained. Here, we found that BAMM often produced homogeneous speciation and extinction rates for clades with few rate shifts; arguably this could reduce our power to detect small differences in extinction rates among closely related taxa [@Rabosky_BAMM_flawed_2017; @Rabosky_diversification_2018]. The ability to detect extinction rates rarely improves when fossil records are used, as many clades (*e.g.* birds) lack the stratographic sampling across time to statistically calculate extinction rates. But, there are exceptions: ostracods --- a group of marine invertebrates --- have extensive fossil records and show identifiable sexual dimorphism. Across 93 species of ostracods, @Martins_2018 found that ostracod taxa with larger sexual dimorphism (representing exaggerated investment by males in reproductive organs) had higher extinction rates; implying that sexual selection increases extinction risk. Alternatively, when comparative studies have assessed the relationship between sexual selection and extinction in extant birds [@Doherty_2003; @Mitra_1996; @Morrow_2003] and mammals [@Bro-Jorgensen_2014; @Morrow_2004] there has been no consensus. Unfortunately, these methods often rely on extinction threat status from the International Union for Conservation of Nature (IUCN) Red List [*e.g.*, @Morrow_2003; @Bro-Jorgensen_2014; @Morrow_2004] and may be biased to species under greater anthropogenic threat, culturally valued or well researched.  

Improvements in estimating tip-rates of speciation has allowed us to revisit the association between sexual selection and speciation. With high power and alongside extensive ecological predictors we find support that male-biased sexual selection predicts speciation. If sexual selection promotes speciation through improvements in fitness and adaptation the implications are manifold with sexual selection a potentially valuable utility in conservation [*reviewed in*, @Holman_Kokko_2013] and captive breeding programs for threatened species [*reviewed in*, @Charge_2014]. Furthermore, our finding that high speciation rate is associated with smaller range size has pronounced significance to the future survival of these rapidly speciating species in a world with increased habitat loss and anthropogenic stress. Range size is the best predictor of extinction risk [@Harris_2008] and the association found here ensues that many newly speciated clades may be at greater risk of extinction due to their reduced range being impacted by anthropogenic effects.  


<!-- Despite the strong predictions that sexual selection is more likely to increase speciation than not **cite all those paper**, there are countervailing arguments that sexual selection may dampen speciation rate. Studies have suggested that increased selection on males through sexual selection may elevate inter-population mating rates as males seek to overcome local gene flow between populations and impede speciation [@Parker_1998; @Servedio_2014]. **How?** Sexual selection may also lead to the evolution of traits that constrain further divergence or adaptation (i.e. lead to an evolutionary dead end) **CITE**. -->

\newpage
# References
<div id="refs"></div>

\newpage
\nolinenumbers

#Critical analysis

\epigraph{[On Darwinism]... But it by no means follows that slight differences in the shape, pattern, or colours of the ornamental plumes are what lead a female to give the preference to one male over another; still less that all the females of a species, or the great majority of them, over a wide area of country, and for many successive generations, prefer exactly the same modification of the colour or ornament.\\ 
--- \large\textsc{Alfred Russel Wallace}}


##Strengths and limitations

Perhaps one of the biggest unravelings of this project was the decoupling of male-biased sexual selection from sexual dichromatism, remarkably this same controversy engrossed Wallace and Darwin 130 years ago [@Kottler_1980]. The widespread use of sexual dichromatism as a proxy for sexual selection often goes unchallenged as our instinctive Darwinian minds reminisce of peacocks and birds of paradise; my thoughts were such when I began this scientific inquiry. Although, sexual dichromatism measurements from colour drawings were always going to be a less than perfect estimate of sexual selection, across 5,831 species I anticipated a signal would permeate through the noise. Alas, this was not so and male-biased sexual selection and sexual dichromatism were very different measures (see \autoref{Path_Analysis} in main text). With this in mind, the practical use of sexual dichromatism in macroevolutionary research is severely weakened. This finding is particularly pertinent as efficient proxy measurements are incredibly valuable in comparative analyses: that's because they increase the accessibility, available sample size and transferability of a study, making it more conducive to research synthesis. But, as Wallace remarks, the matter is inevitably more complex despite the irresistibility of the Darwinian argument\footnote{Wallace was initially supportive of the evolution of sexual dichromatism as a result of mate choice but later took more interest in a view where natural selection on predator-prone nesting females generated dullness in females but not males.} [@Kottler_1980; @Caro_2017]. On the bright side, the multivariate measure of male-biased sexual selection (sexual dimorphism, social polygyny and [lack of] paternal care) is a dataset that would benefit from being expanded across birds.  

Not only are the measurements of sexual selection under a cloud of uncertainty, the estimates of speciation and extinction are another point of controversy. Macroevolutionary research is a field plagued by methodological uncertainty and conflicts. Originally, I had planned to continue my meta-analysis by investigating extinction rate across a large taxonomic group. There were signs that extinction rate could be measured from phylogenetic methods with relative confidence [@Pyron_2016]. However, these hopes soon dissipated, and with them the seeming \emph{raison d'\^{e}tre} of the study. Extinction rate is arguably the best measure of population fitness. And while a high profile study has measured extinction rate in experimental evolution [@Lumley_2015], it has been rarely measured accurately over evolutionarily meaningful timescales [*but see* @Martins_2018]. We included measurements of extinction rate within the paper, however these findings were played down. The reason for this movement away from extinction and towards speciation is the controversy surrounding extinction rate measures as well as phylogentic uncertainty. Measuring extinction rates within the bird phylogeny is problematic because of the nature of phylogenetic construction: for passerine birds a birth-only model of tree construction and incomplete genetic taxon sampling are large barriers that limit the ability to use model-based methods to detect extinction rate [@Beaulieu_2015]. Furthermore, the very detection of absence of data --- which is what such methods attempt to do --- is a hard sell both conceptually and methodically come peer review: see @Rabosky_Extinction_2016 for a cautionary tale on measuring extinction rate with ``BAMM``. The mechanisms and rates at which speciation and extinction occur are an active area of research. In a recent pre-print @Diaz_2018 used ``BAMM`` across 104 time-calibrated molecular phylogenies and found that despite variation in ecology, biogeography and taxonomy, younger clades consistently had higher rates of speciation and extinction. This finding of time-dependency in rates of diversification makes comparative analyses between clades challenging and calls into question countless studies [@Diaz_2018]. Similar to Wallace's view of sexual dichromatism we are left with a view of diversification rate measures where we cannot yet account for the underlying true variation; which is vastly more complex than we can currently measure.  

As with sexual dichromatism and macroevolutionary rates, the most severe limitation for environmental variation was the coarseness of the measures. In total, for 5,831 species we extracted 338,203,831 point measures\footnote{5,831 species x 1000 samples per range x 59 environmental variability measures including bioclimatic predictors now, in the last inter-glacial and the last glacial maximum as well as NPP.} of environmental variability, but these measures may not account for important variation in biotic components such as nutritional resources or predation. Arguably, the methods used here are much better than those traditionally implemented; where the range mid-point is used to obtain a single measure of temperature, precipitation or seasonality or where only one bioclimatic variable is used. I would argue that reducing the multivariate data into several biologically meaningful predictors is a conceptually challenging exercise, but researchers should not feel limited by the amount of raw data that they can access\footnote{This statement applies to species with documented range sizes, which varies across clades but is comprehensive for birds, mammals, amphibians and many marine groups. The \href{http://www.iucnredlist.org/technical-documents/spatial-data}{IUCN} has a large and accessible database for research use. Details of how we extracted data from these ranges is provided as a potentially useful resource in the \href{https://justincally.github.io/SexualSelection_Speciation/}{ESM}.}. In fact, previous to our study on birds the same methodology was applied to ~ 100 species of bovids with speciation, extinction and environmental variability estimates obtained. This study was prematurely halted as there was homogeneity in the response variable (speciation and extinction rates) across the smaller bovid phylogeny. However, this workflow was easily transferred over to passerine birds with similar methods used for extracting environmental predictors. The use of extensive bioclimatic predictors and spatial data in macroevolutionary research is imperative as we scale up studies. At very least, if bioclimatic variables do not encapsulate key ecological parameters (*e.g.*, resources, predation, habitat structure) these predictors may account for some of the noise in the dataset and may help isolate the effect of the key moderator variables of interest.  

##Future Directions

I had initially envisaged that this comparative study would allow for the reliable measure of extinction rate, use multiple taxonomic groups and more robust measures of sexual selection [*see* @Anthes_2016]. As such, many questions regarding this topic remain unanswered. Here I discuss the broader directions that we may follow in order to consolidate our understanding of sexual selection and its effects on fitness and diversification. I will draw heavily on the discussions from a Royal Society meeting on _'Sexual selection: patterns in the history of life'_\footnote{Specifically, the following two sections are spurred from dialogue with \href{https://paleobiology.si.edu/staff/individuals/hunt.cfm}{Dr Gene Hunt} and \href{https://www.earth.ox.ac.uk/people/erin-saupe/}{Associate Professor Erin E. Saupe}} in the UK this year. This meeting spurred further inquiry into the subject and how interdisciplinary approaches can be harnessed to liberate ourselves from conventional comparative methodologies.  

The study by @Martins_2018 has already been referred to in the main text of both papers and for good reason. This elegant study was able to do what no one else has; reliably measure extinction rate over meaningful time scales. Using fossil ostracods with various levels of sexual dimorphism, @Martins_2018 found that species with high levels of sexual dimorphism were quickly swept to extinction. From stratographic occurrence data a capture–mark–recapture model was used to determine the rate of extinction for 93 species. Their finding challenges the results from experimental evolution studies [@Jarzebowska_2010; @Plesnar_2012; @Lumley_2015] and our meta-analysis that find sexual selection mitigates extinction. In future, it would be incredibly valuable to see whether other groups of marine invertebrates have the fossil data and recognisable sexual dimorphism to conduct such a study. In the interim I would be eager to see how ``BAMM`` performs on an ostracod phylogeny and whether the same positive association between extinction rate and sexual dimorphism could be detected from phylogenies. For me, this will be a true test of the applicability of ``BAMM`` and a key step in the effort to reliably measure extinction rates across a wider variety of species. 

One aspect and only foreseeable shortcoming of the ostracod study is that it did not account for environmental variability; a challenging proposal for extinct species nevertheless. However, the use of paleoclimate models in evolution is now a reality; with recent studies incorporating averaged values across multiple paleoclimate models as predictors of speciation [*see* @quintero_2018]. While the uncertainty surrounding paleoclimates was beyond the scope of the study, future studies should remain vigilant of the everlasting need to incorporate key ecological processes in macroevolutionary research [*reviewed in* @Weber_2017]. In our study on passerine birds we found that range size is negatively associated with speciation. The role of range size in speciation may be further investigated through ancestral geographic range reconstruction [@Quintero_2015], as ancestral ranges may be beneficial in understanding modes of speciation and the causality of range size expansions and contractions [@Losos_2003]. Within Palaeobiology the role of range size and niche breadth on diversification patterns has been the subject of recent interest [*e.g.* @Saupe_2015; @Saupe_2016]. Across 92 bivalve species that lived during a mid-Pliocene warming period, @Saupe_2015 used environmental niche modelling to assess the impact of ecological processes on extinction. Harnessing ecological niche modelling in macroevolutionary studies across extant taxa such as passerine birds is a daunting challenge but offers an Eco-evo synthesis that may be particularly pertinent in questions relating to extinction; especially if the taxonomic group under inquiry is of high conservation value, for which the songbirds certainly are.

